### ISSUE TITLE
java.lang.StackOverflowError while editing Quarkus extension

### ISSUE THREAD

**Issue by gastaldi** [redhat-developer/intellij-quarkus#1110]
I was browsing the sources in https://github.com/quarkiverse/quarkus-ironjacamar and had this error in the error log: 

```java
  Error executing task com.intellij.openapi.project.SmartModeScheduler$RunnableDelegate@35d7b1d1
  
  java.lang.StackOverflowError
at kotlin.jvm.internal.Intrinsics.areEqual(Intrinsics.java:169)
at kotlinx.coroutines.internal.ThreadLocalElement.get(ThreadContext.kt:127)
at kotlin.coroutines.CombinedContext.get(CoroutineContextImpl.kt:120)
at com.intellij.openapi.progress.Cancellation.currentJob(Cancellation.java:26)
at com.intellij.openapi.progress.Cancellation.checkCancelled(Cancellation.java:35)
at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:133)
at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:231)
at com.intellij.openapi.progress.ProgressIndicatorProvider.checkCanceled(ProgressIndicatorProvider.java:23)
at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:168)
at com.intellij.psi.impl.compiled.ClsJavaCodeReferenceElementImpl.multiResolve(ClsJavaCodeReferenceElementImpl.java:215)
at com.intellij.psi.impl.compiled.ClsJavaCodeReferenceElementImpl.advancedResolve(ClsJavaCodeReferenceElementImpl.java:203)
at com.intellij.psi.impl.compiled.ClsJavaCodeReferenceElementImpl.resolve(ClsJavaCodeReferenceElementImpl.java:228)
at com.intellij.psi.impl.source.PsiClassReferenceType.rawType(PsiClassReferenceType.java:190)
at com.intellij.psi.util.TypeConversionUtil$3.visitClassType(TypeConversionUtil.java:1424)
at com.intellij.psi.util.TypeConversionUtil$3.visitClassType(TypeConversionUtil.java:1411)
at com.intellij.psi.PsiClassType.accept(PsiClassType.java:225)
at com.intellij.psi.util.TypeConversionUtil.erasure(TypeConversionUtil.java:1411)
at com.intellij.psi.util.TypeConversionUtil.erasure(TypeConversionUtil.java:1405)
at com.intellij.psi.util.ClassUtil.lambda$toBinary$2(ClassUtil.java:326)
at java.base/java.util.Optional.map(Optional.java:260)
at com.intellij.psi.util.ClassUtil.toBinary(ClassUtil.java:326)
at com.intellij.psi.util.ClassUtil.getBinaryPresentation(ClassUtil.java:320)
at com.intellij.psi.util.ClassUtil.getAsmMethodSignature(ClassUtil.java:269)
at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.utils.PsiTypeUtils.getSourceMethod(PsiTypeUtils.java:143)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:189)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)
at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:217)

```

**Comment by angelozerr** [comment]
@fbricon thanks for having fixed the issue. I wonder if we have the same problem in LSP4MP?

**Comment by fbricon** [comment]
@angelozerr yup https://github.com/redhat-developer/quarkus-ls/issues/924
