### ISSUE TITLE
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'fragment' of com/intellij/ui/SimpleColoredComponent.append must not be null

### ISSUE THREAD

**Issue by marudsa** [redhat-developer/intellij-quarkus#1124]
This error occurs after I want to create a project using quarkus tools, it won't let me use it. I use the intellij community version 2023.2

java.lang.IllegalArgumentException: Argument for @NotNull parameter 'fragment' of com/intellij/ui/SimpleColoredComponent.append must not be null
	at com.intellij.ui.SimpleColoredComponent.$$$reportNull$$$0(SimpleColoredComponent.java)
	at com.intellij.ui.SimpleColoredComponent.append(SimpleColoredComponent.java)
	at com.redhat.devtools.intellij.quarkus.module.QuarkusModuleInfoStep$3.customizeCellRenderer(QuarkusModuleInfoStep.java:144)
	at com.redhat.devtools.intellij.quarkus.module.QuarkusModuleInfoStep$3.customizeCellRenderer(QuarkusModuleInfoStep.java:136)
	at com.intellij.ui.ColoredListCellRenderer.getListCellRendererComponent(ColoredListCellRenderer.java:45)
	at com.intellij.openapi.ui.ComboBoxWithWidePopup$AdjustingListCellRenderer.getListCellRendererComponent(ComboBoxWithWidePopup.java:83)
	at java.desktop/javax.swing.plaf.basic.BasicComboBoxUI.getDisplaySize(BasicComboBoxUI.java:1446)
	at java.desktop/javax.swing.plaf.basic.BasicComboBoxUI.getMinimumSize(BasicComboBoxUI.java:999)
	at com.intellij.ide.ui.laf.darcula.ui.DarculaComboBoxUI.getPreferredSize(DarculaComboBoxUI.java:582)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1721)
	at com.intellij.openapi.ui.ComboBox.getPreferredSize(ComboBox.java:275)
	at java.desktop/java.awt.GridBagLayout.GetLayoutInfo(GridBagLayout.java:1111)
	at java.desktop/java.awt.GridBagLayout.getLayoutInfo(GridBagLayout.java:906)
	at java.desktop/java.awt.GridBagLayout.preferredLayoutSize(GridBagLayout.java:726)
	at java.desktop/java.awt.Container.lambda$preferredSize$4(Container.java:1826)
	at java.desktop/sun.awt.SunToolkit.performWithTreeLock(SunToolkit.java:2155)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1824)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1723)
	at com.intellij.ui.components.JBViewport.getPreferredSizeWithoutScrollBars(JBViewport.java:523)
	at com.intellij.ui.components.JBViewport.getPreferredScrollableViewportSize(JBViewport.java:518)
	at com.intellij.ui.components.JBViewport$1.preferredLayoutSize(JBViewport.java:65)
	at java.desktop/java.awt.Container.lambda$preferredSize$4(Container.java:1826)
	at java.desktop/sun.awt.SunToolkit.performWithTreeLock(SunToolkit.java:2155)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1824)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1723)
	at com.intellij.ui.components.JBScrollPane$Layout.preferredLayoutSize(JBScrollPane.java:822)
	at java.desktop/java.awt.Container.lambda$preferredSize$4(Container.java:1826)
	at java.desktop/sun.awt.SunToolkit.performWithTreeLock(SunToolkit.java:2155)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1824)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1723)
	at java.desktop/java.awt.BorderLayout.layoutContainer(BorderLayout.java:820)
	at java.desktop/java.awt.Container.layout(Container.java:1541)
	at java.desktop/java.awt.Container.doLayout(Container.java:1530)
	at java.desktop/java.awt.Container.validateTree(Container.java:1725)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.lambda$validate$3(Container.java:1659)
	at java.desktop/sun.awt.SunToolkit.performWithTreeLock(SunToolkit.java:2155)
	at java.desktop/java.awt.Container.validate(Container.java:1648)
	at java.desktop/java.awt.CardLayout.show(CardLayout.java:556)
	at com.intellij.ui.JBCardLayout.show(JBCardLayout.java:184)
	at com.intellij.ui.JBCardLayout$1.actionPerformed(JBCardLayout.java:108)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:789)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:759)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:121)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
	at java.desktop/java.awt.Dialog.lambda$show$2(Dialog.java:1081)
	at java.desktop/sun.awt.SunToolkit.performOnMainThreadIfNeeded(SunToolkit.java:2164)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1041)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:743)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:468)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1685)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1643)
	at com.intellij.openapi.ui.DialogWrapper.showAndGet(DialogWrapper.java:1657)
	at com.intellij.ide.impl.NewProjectUtil.createNewProject(NewProjectUtil.kt:68)
	at com.intellij.ide.actions.NewProjectAction.actionPerformed(NewProjectAction.java:24)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:339)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:313)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:362)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:313)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$performAction$5(ActionMenuItem.java:300)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:226)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction(ActionMenuItem.java:293)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$new$0(ActionMenuItem.java:68)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$4(ActionMenuItem.java:115)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:115)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:526)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:558)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6657)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4954)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4581)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4522)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2808)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:791)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:762)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:633)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:588)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
![Captura de pantalla 2023-08-23 134420](https://github.com/redhat-developer/intellij-quarkus/assets/110506792/52d5cc02-4d85-4400-b349-27847d681277)

**Comment by fbricon** [comment]
or did you set a different url for the quarkus endpoint?

**Comment by marudsa** [comment]
Hi fbricon, I don't have a proxy, I suspect my internet connection (it may be slow where I am) but at this moment an ide update to 2023.2.1 appeared, I'm going to try.

**Comment by marudsa** [comment]
the same problem persists:

![image](https://github.com/redhat-developer/intellij-quarkus/assets/110506792/9aee2619-5392-4951-b686-18ef1c1dcff3)

![image](https://github.com/redhat-developer/intellij-quarkus/assets/110506792/f1350d42-36ce-49b3-829e-987ddee0c423)

![image](https://github.com/redhat-developer/intellij-quarkus/assets/110506792/da45a4a4-fe74-4dc4-99d0-d9e793356611)

![image](https://github.com/redhat-developer/intellij-quarkus/assets/110506792/de31832a-f0da-4126-8fcf-85f819eb3f5f)

**Comment by marudsa** [comment]
Additional if I try to access the page from a browser I can do it without problem:
![image](https://github.com/redhat-developer/intellij-quarkus/assets/110506792/f0224772-6cb0-4106-a439-d0cc8ff08892)

**Comment by fbricon** [comment]
I can reproduce it. Looks like the code.quarkus.io/api/streams returns something different.

**Comment by fbricon** [comment]
@marudsa you can follow these [instructions](https://github.com/redhat-developer/intellij-quarkus#testing-the-ci-builds) to try the CI build from https://github.com/redhat-developer/intellij-quarkus/actions/runs/5956593839

**Comment by marudsa** [comment]
@fbricon Carry out the test by manually uploading the indicated plugin and in this way it worked! thank you so much!!

![image](https://github.com/redhat-developer/intellij-quarkus/assets/110506792/74531cf0-fd28-4507-9430-e12eb4a75f09)


![image](https://github.com/redhat-developer/intellij-quarkus/assets/110506792/64257d78-4aab-4bb6-83c4-4ddf76c071b8)

**Comment by fbricon** [comment]
@marudsa thanks for confirming. While I merged the fix, the original behavior has been restored for existing versions (see #https://github.com/quarkusio/code.quarkus.io/issues/1241)
