### ISSUE TITLE
NoClassDefFoundError: org/apache/commons/lang/exception/ExceptionUtils in IJ 2023.3 EAP

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/intellij-quarkus#1191]
Build #IC-233.8264.8, built on September 28, 2023

Tried to restart LSP4MP

```
java.lang.NoClassDefFoundError: org/apache/commons/lang/exception/ExceptionUtils
	at com.redhat.devtools.intellij.lsp4ij.console.LSPConsoleToolWindowPanel$ConsoleContentPanel.showError(LSPConsoleToolWindowPanel.java:252)
	at com.redhat.devtools.intellij.lsp4ij.console.LSPConsoleToolWindowPanel.showError(LSPConsoleToolWindowPanel.java:291)
	at com.redhat.devtools.intellij.lsp4ij.console.explorer.LanguageServerExplorer.showError(LanguageServerExplorer.java:187)
	at com.redhat.devtools.intellij.lsp4ij.console.explorer.LanguageServerExplorerLifecycleListener.showError(LanguageServerExplorerLifecycleListener.java:167)
	at com.redhat.devtools.intellij.lsp4ij.console.explorer.LanguageServerExplorerLifecycleListener.lambda$handleError$1(LanguageServerExplorerLifecycleListener.java:77)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)

```

**Comment by angelozerr** [comment]
It is working for me?

**Comment by angelozerr** [comment]
Ok sorry the problem comes from IC-233.8264.8,
