### ISSUE TITLE
Argument for @NotNull parameter 'file' of com/intellij/openapi/vfs/VfsUtilCore.virtualToIoFile must not be null

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/intellij-quarkus#1228]
I regularly see those errors:

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'file' of com/intellij/openapi/vfs/VfsUtilCore.virtualToIoFile must not be null
	at com.intellij.openapi.vfs.VfsUtilCore.$$$reportNull$$$0(VfsUtilCore.java)
	at com.intellij.openapi.vfs.VfsUtilCore.virtualToIoFile(VfsUtilCore.java)
	at com.redhat.devtools.intellij.lsp4ij.LSPIJUtils.toUri(LSPIJUtils.java:124)
	at com.redhat.devtools.intellij.lsp4ij.operations.codelens.LSPCodelensInlayProvider$1.collect(LSPCodelensInlayProvider.java:79)
	at com.intellij.codeInsight.hints.CollectorWithSettings.collectHints(InlayHintsUtils.kt:91)
	at com.intellij.codeInsight.hints.InlayHintsPass.doCollectInformation$lambda$0(InlayHintsPass.kt:46)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:142)
```

**Comment by fbricon** [comment]
must have been a stale error from a previous run

**Comment by fbricon** [comment]
got this one:

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'file' of com/redhat/devtools/intellij/lsp4ij/LanguageServiceAccessor.getLanguageServers must not be null
	at com.redhat.devtools.intellij.lsp4ij.LanguageServiceAccessor.$$$reportNull$$$0(LanguageServiceAccessor.java)
	at com.redhat.devtools.intellij.lsp4ij.LanguageServiceAccessor.getLanguageServers(LanguageServiceAccessor.java)
	at com.redhat.devtools.intellij.lsp4ij.operations.navigation.LSPGotoDeclarationHandler.getGotoDeclarationTargets(LSPGotoDeclarationHandler.java:62)
	at com.intellij.codeInsight.navigation.impl.GtdProvidersKt.fromGTDProvidersInner(gtdProviders.kt:32)
```

**Comment by angelozerr** [comment]
Indeed it is an another usecase. Let me fix that.
