### ISSUE TITLE
Too many non-blocking read actions submitted at once

### ISSUE THREAD

**Issue by starksm64** [redhat-developer/intellij-quarkus#1246]
Quite often on the load of the quarkus core project I'm getting the following error being shown by Intellij:

```java
java.lang.Throwable: Too many non-blocking read actions submitted at once. Please use coalesceBy, BoundedTaskExecutor or another way of limiting the number of concurrently running threads.: 11 with similar stack traces are currently active
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.intellij.openapi.application.impl.SubmissionTracker.preventTooManySubmissions(SubmissionTracker.java:45)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.<init>(NonBlockingReadActionImpl.java:272)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl.submit(NonBlockingReadActionImpl.java:227)
	at com.redhat.devtools.intellij.lsp4ij.internal.PromiseToCompletableFuture.nonBlockingReadActionPromise(PromiseToCompletableFuture.java:156)
	at com.redhat.devtools.intellij.lsp4ij.internal.PromiseToCompletableFuture.init(PromiseToCompletableFuture.java:79)
	at com.redhat.devtools.intellij.lsp4ij.client.LSPCompletableFuture.<init>(LSPCompletableFuture.java:30)
	at com.redhat.devtools.intellij.lsp4ij.client.IndexAwareLanguageClient.runAsBackground(IndexAwareLanguageClient.java:54)
	at com.redhat.devtools.intellij.qute.lsp.QuteLanguageClient.getDataModelProject(QuteLanguageClient.java:153)
	at jdk.internal.reflect.GeneratedMethodAccessor2951.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at com.redhat.devtools.intellij.lsp4ij.LanguageServerWrapper.lambda$start$1(LanguageServerWrapper.java:353)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by fbricon** [comment]
we've tried to fix that error before. Which version of quarkus tools are you using?

**Comment by starksm64** [comment]
This is for the current quarkus main repo(
https://github.com/quarkusio/quarkus.git) which is just post 3.5.0. It is
not for a specific quarkus app.

**Comment by starksm64** [comment]
The plugin version is 1.29.0.583

**Comment by gastaldi** [comment]
I can confirm this also happens in 1.30.1

**Comment by angelozerr** [comment]
Thanks @gastaldi, I need to undertsnad how to reproduce this issue.

**Comment by gastaldi** [comment]
@angelozerr I get this error when opening the https://github.com/quarkusio/quarkus project in IntelliJ

**Comment by angelozerr** [comment]
@gastaldi  @starksm64  could you please install:

 * https://github.com/redhat-developer/intellij-quarkus?tab=readme-ov-file#testing-nightly-builds
 * https://github.com/redhat-developer/lsp4ij?tab=readme-ov-file#testing-the-ci-builds

and tell me if it is working better.

Any feedback are welcome!

**Comment by angelozerr** [comment]
> @angelozerr after updating the exception message no longer appears to me 

Thats great! Thanks @gastaldi for your feedback.
