### ISSUE TITLE
Error while consuming 'textDocument/inlayHint' with language server 'Qute support'

### ISSUE THREAD

**Issue by ksdev-pl** [redhat-developer/intellij-quarkus#1380]
Hello.

While editing a qute template and writing `{#i` with the intention to write `{#include...` (exception was after `{#i`).

![image](https://github.com/user-attachments/assets/0eb47858-ac94-4664-9c30-59ad579012d6)

```
Error while consuming 'textDocument/inlayHint' with language server 'Qute support'

org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Internal error.
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at com.redhat.devtools.lsp4ij.LanguageServerWrapper.lambda$start$1(LanguageServerWrapper.java:260)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```
```
IntelliJ IDEA 2024.2.1 (Ultimate Edition)
Build #IU-242.21829.142, built on August 28, 2024
Runtime version: 21.0.3+13-b509.11 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 6.10.6-200.fc40.x86_64
Kotlin plugin: K2 mode (Beta)
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 16
Registry:
  debugger.new.tool.window.layout=true
  vcs.log.index.enable=true
  ide.experimental.ui=true
  i18n.locale=
  terminal.new.ui=true
Non-Bundled Plugins:
  com.supermaven.intellij (1.38)
  com.redhat.devtools.intellij.telemetry (1.2.1.62)
  com.redhat.devtools.lsp4ij (0.4.0)
  AceJump (3.8.19)
  com.redhat.devtools.intellij.quarkus (2.0.2)
  com.jetbrains.packagesearch.intellij-plugin (242.0.12)
Kotlin: 242.21829.142-IJ
Current Desktop: GNOME
```

**Comment by angelozerr** [comment]
Thanks @ksdev-pl for having reported the issue.

The problem comes from the Qute language server. I created the issue at https://github.com/redhat-developer/quarkus-ls/issues/991

**Comment by angelozerr** [comment]
@ksdev-pl this bug can be very annoying  when you are typing Qute section tag. By waiting for the fix, I suggest that you write

`for` instead of `{#` to generate the `{#for` section:

 * you will avoid the bug
 * it is faster to write `for` instead of `{#for`

**Comment by angelozerr** [comment]
Fixed with https://github.com/redhat-developer/quarkus-ls/pull/992

**Comment by angelozerr** [comment]
@ksdev-pl please [install nightly-builds](https://github.com/redhat-developer/intellij-quarkus?tab=readme-ov-file#testing-nightly-builds), it should fix your issue.
