### ISSUE TITLE
Is Find Usages broken?

### ISSUE THREAD

**Issue by kristofvb** [redhat-developer/intellij-quarkus#1383]
Hi,

I am using IntelliJ IDEA 2024.2.1 (Ultimate Edition) with Quarkus Tools
  com.redhat.devtools.lsp4ij (0.4.0)
  com.redhat.devtools.intellij.quarkus (2.0.2)

Whenever I try to use Find Usages it turns up with an empty result. Am I missing some other plugins or some setting to make this work?

I have already tried rebuilding the caches to no avail. Disabling the Quarkus Tools plugin resolves the issue.

Thanks for your help.

**Comment by angelozerr** [comment]
You are using find usages with java files? If yes could you share your project and tell me which file and which symbol you are using to execute find usages.

Thanks.

**Comment by angelozerr** [comment]
@kristofvb we already some issues with find usages causes by lsp4ij,  it seems that there is a new usecase which causes again a problem.

I am waiting for your feedback to reproduce your issue and try to fix it.

Thanks!

**Comment by kristofvb** [comment]
I am not able to share my project but you can reproduce it by generating a sample project as described in the [Get Started](https://quarkus.io/get-started/) guide.

**Comment by angelozerr** [comment]
If you do find usages on java declaration class method, is it working?

Where are you doing find usages? On field declaration, method, etc ?

**Comment by angelozerr** [comment]
I have tested with IntelliJ Ultimate IDEA 2024.2 and it works great.

Please give me a screenshot where you do the find usages.

**Comment by kristofvb** [comment]
Extracted the return statement to a method and applied Find Usages to it.

![Screenshot 2024-09-03 at 08 03 54](https://github.com/user-attachments/assets/382986fa-9997-4aae-ac6f-98e2373b1bee)

**Comment by angelozerr** [comment]
I don't understand, it works for me:

![image](https://github.com/user-attachments/assets/3cc15363-5116-471c-902d-d4036549234b)

@fbricon have you the same problem?

**Comment by kristofvb** [comment]
It might be an interaction with some other plugin. I'll see if I can isolate it somehow.

**Comment by angelozerr** [comment]
Thanks @kristofvb !

**Comment by kristofvb** [comment]
I disabled all plugins except those I need to reproduce this. Still no results.

I finally looked at the IntelliJ logs and found this

```
2024-09-03 14:16:14,688 [  14090]   WARN - com.redhat.devtools.lsp4ij.internal.PromiseToCompletableFuture - Restart non blocking read action for 'Computing Java file info' with attempt 1/5.
com.intellij.openapi.progress.ProcessCanceledException
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.throwIfCanceled(AbstractProgressIndicatorBase.java:172)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.checkCanceled(AbstractProgressIndicatorBase.java:162)
	at com.intellij.openapi.progress.util.ProgressWrapper.checkCanceledRaw(ProgressWrapper.java:70)
	at com.intellij.openapi.progress.util.ProgressWrapper.checkCanceled(ProgressWrapper.java:77)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:336)
	at com.intellij.openapi.progress.ProgressIndicatorProvider.checkCanceled(ProgressIndicatorProvider.java:41)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:162)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.internal.core.ls.PsiUtilsLSImpl.resolveCompilationUnit(PsiUtilsLSImpl.java:192)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManagerForJava.fileInfo(PropertiesManagerForJava.java:84)
	at com.redhat.devtools.intellij.quarkus.lsp.QuarkusLanguageClient.lambda$getJavaFileInfo$12(QuarkusLanguageClient.java:220)
	at com.redhat.devtools.lsp4ij.internal.PromiseToCompletableFuture.lambda$nonBlockingReadActionPromise$2(PromiseToCompletableFuture.java:144)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped(NonBlockingReadActionImpl.java:840)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call(NonBlockingReadActionImpl.java:872)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:604)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$4(NonBlockingReadActionImpl.java:567)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:93)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:155)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:138)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:217)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:135)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:93)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:567)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:466)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$2(NonBlockingReadActionImpl.java:481)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by angelozerr** [comment]
This trace is just a warn which says that Quarkus properties cannot be loaded and it retries it, but there are no link with find usages -(

How are you using Find Usages, with contextual menu, shortcut?

**Comment by kristofvb** [comment]
Ah, should have tried that earlier. The context menu and the Edit -> Find Usages menu work, the cmd+option+F7 shortcut did not work. So I am actually talking about the 'Show Usages' functionality. After using one of the menu items then the shortcut works too. Does any of this make sense?
