### ISSUE TITLE
java.lang.Throwable: Must be executed under progress indicator

### ISSUE THREAD

**Issue by stephenc** [redhat-developer/intellij-quarkus#223]
Quarkus Tools 1.0.4.45

There are 100's of these:

```
java.lang.Throwable: Must be executed under progress indicator: com.intellij.openapi.progress.EmptyProgressIndicator@4a3b36b5. Please see e.g. ProgressManager.runProcess()
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:143)
	at com.intellij.openapi.progress.impl.CoreProgressManager.assertUnderProgress(CoreProgressManager.java:966)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processFilesConcurrentlyDespiteWriteActions(PsiSearchHelperImpl.java:426)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processPsiFileRoots(PsiSearchHelperImpl.java:392)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processCandidates(PsiSearchHelperImpl.java:889)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processGlobalRequests(PsiSearchHelperImpl.java:859)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processGlobalRequestsOptimized(PsiSearchHelperImpl.java:825)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processRequests(PsiSearchHelperImpl.java:750)
	at com.intellij.psi.search.SearchRequestQuery.processResults(SearchRequestQuery.java:24)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:96)
	at com.intellij.util.AbstractQuery.delegateProcessResults(AbstractQuery.java:119)
	at com.intellij.util.MergeQuery.processResults(MergeQuery.java:26)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:96)
	at com.intellij.util.AbstractQuery.delegateProcessResults(AbstractQuery.java:119)
	at com.intellij.util.UniqueResultsQuery.processResults(UniqueResultsQuery.java:35)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:96)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:88)
	at com.intellij.util.AbstractQuery.findAll(AbstractQuery.java:30)
	at com.intellij.util.AbstractQuery.iterator(AbstractQuery.java:41)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
	at com.redhat.devtools.intellij.quarkus.search.internal.restclient.java.MicroProfileRestClientDiagnosticsParticipant.validateInterfaceType(MicroProfileRestClientDiagnosticsParticipant.java:201)
	at com.redhat.devtools.intellij.quarkus.search.internal.restclient.java.MicroProfileRestClientDiagnosticsParticipant.collectDiagnostics(MicroProfileRestClientDiagnosticsParticipant.java:100)
	at com.redhat.devtools.intellij.quarkus.search.internal.restclient.java.MicroProfileRestClientDiagnosticsParticipant.collectDiagnostics(MicroProfileRestClientDiagnosticsParticipant.java:90)
	at com.redhat.devtools.intellij.quarkus.search.core.PropertiesManagerForJava.lambda$null$4(PropertiesManagerForJava.java:106)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.redhat.devtools.intellij.quarkus.search.core.PropertiesManagerForJava.lambda$collectDiagnostics$6(PropertiesManagerForJava.java:105)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:869)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:140)
	at com.redhat.devtools.intellij.quarkus.search.core.PropertiesManagerForJava.collectDiagnostics(PropertiesManagerForJava.java:93)
	at com.redhat.devtools.intellij.quarkus.search.core.PropertiesManagerForJava.diagnostics(PropertiesManagerForJava.java:79)
	at com.redhat.devtools.intellij.quarkus.lsp.QuarkusLanguageClient.lambda$getJavaDiagnostics$3(QuarkusLanguageClient.java:133)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by jeffmaury** [comment]
Duplicates #181
