### ISSUE TITLE
IntelliJ freezes when opening Quarkus projects

### ISSUE THREAD

**Issue by gnieser** [redhat-developer/intellij-quarkus#416]
Hello,

I very frequently get complete freeze of IntelliJ when I open Quarkus projects. JetBrains supports has identified the likely root cause being Quarkus Tools plugins so I am sharing the logs here.

```
"AWT-EventQueue-0" prio=0 tid=0x0 nid=0x0 blocked
     java.lang.Thread.State: BLOCKED
 on java.lang.Object@be5b5de owned by "JobScheduler FJ pool 0/7" Id=34
    at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:67)
    at com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageServerWrapper.lambda$null$0(LanguageServerWrapper.java:233)
    at com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageServerWrapper$$Lambda$1919/0x000000010199e840.consume(Unknown Source)
....
"JobScheduler FJ pool 0/7" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE
 (in native)
    at java.base@11.0.11/java.io.FileOutputStream.writeBytes(Native Method)
    at java.base@11.0.11/java.io.FileOutputStream.write(FileOutputStream.java:354)
    at java.base@11.0.11/java.io.BufferedOutputStream.write(BufferedOutputStream.java:123)
    at java.base@11.0.11/java.io.FilterOutputStream.write(FilterOutputStream.java:108)
    at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:68)
    at com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageServerWrapper.lambda$null$0(LanguageServerWrapper.java:233)
    at com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageServerWrapper$$Lambda$1919/0x000000010199e840.consume(Unknown Source)
    at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.notify(RemoteEndpoint.java:126)
    at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:88)
    at com.sun.proxy.$Proxy103.didOpen(Unknown Source)
    at com.redhat.devtools.intellij.quarkus.lsp4ij.DocumentContentSynchronizer.lambda$new$0(DocumentContentSynchronizer.java:69)
    at com.redhat.devtools.intellij.quarkus.lsp4ij.DocumentContentSynchronizer$$Lambda$2095/0x0000000101aa2440.accept(Unknown Source)
    at java.base@11.0.11/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
    at java.base@11.0.11/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
    at java.base@11.0.11/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base@11.0.11/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base@11.0.11/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base@11.0.11/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base@11.0.11/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

As you may see, the main IDEA thread is blocked by "JobScheduler FJ pool 0/7", where you could see the traces of the plugin:
```
    at com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageServerWrapper.lambda$null$0(LanguageServerWrapper.java:233)
    at com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageServerWrapper$$Lambda$1919/0x000000010199e840.consume(Unknown Source)
```

I am using:
* IntelliJ 2021.1.2
* Quarkus Tools 1.5.0.136

Kind regards!

**Comment by jeffmaury** [comment]
Fixed by 0dae4210adc929da82950f0b3eeb733efed08908
