### ISSUE TITLE
Cannot compute MicroProfile properties for the Java element 'Light Parameter'.

### ISSUE THREAD

**Issue by kny78** [redhat-developer/intellij-quarkus#432]
I get an exception when I start IntelliJ. The bug is supposed to be in IntelliJ.

Error message:
`Cannot compute MicroProfile properties for the Java element 'Light Parameter'.

java.lang.NullPointerException
	at java.base/java.lang.String.endsWith(String.java:1485)
	at com.redhat.devtools.intellij.quarkus.search.core.utils.AnnotationUtils.isMatchAnnotation(AnnotationUtils.java:61)
	at com.redhat.devtools.intellij.quarkus.search.providers.AbstractAnnotationTypeReferencePropertiesProvider.processAnnotation(AbstractAnnotationTypeReferencePropertiesProvider.java:58)
	at com.redhat.devtools.intellij.quarkus.search.providers.AbstractAnnotationTypeReferencePropertiesProvider.collectProperties(AbstractAnnotationTypeReferencePropertiesProvider.java:49)
	at com.redhat.devtools.intellij.quarkus.search.PropertiesManager.collectProperties(PropertiesManager.java:118)
	at com.redhat.devtools.intellij.quarkus.search.PropertiesManager.lambda$null$1(PropertiesManager.java:96)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.redhat.devtools.intellij.quarkus.search.PropertiesManager.lambda$getMicroProfileProjectInfo$2(PropertiesManager.java:96)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:143)
	at com.redhat.devtools.intellij.quarkus.search.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:93)
	at com.redhat.devtools.intellij.quarkus.QuarkusProjectService.lambda$null$4(QuarkusProjectService.java:155)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:936)
	at com.redhat.devtools.intellij.quarkus.QuarkusProjectService.lambda$computeSchema$5(QuarkusProjectService.java:153)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:401)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:393)
	at com.intellij.openapi.project.TrackedEdtActivityService$TrackedEdtActivity.run(TrackedEdtActivityService.java:66)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:886)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:755)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:487)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Comment by kny78** [comment]
I have made a simple NPE fix, which fixes the NPE, but I have not tested this

[https://github.com/redhat-developer/intellij-quarkus/pull/433](https://github.com/redhat-developer/intellij-quarkus/pull/433)
