### ISSUE TITLE
EmptyStackException on Quarkus core project

### ISSUE THREAD

**Issue by gastaldi** [redhat-developer/intellij-quarkus#586]
In Red Hat Quarkus 1.11.0.229 I saw this when opening the Quarkus Core project:

```
Error while visiting node with com.redhat.devtools.intellij.lsp4mp4ij.psi.internal.config.java.MicroProfileConfigASTValidator

java.util.EmptyStackException
	at com.intellij.util.containers.Stack.pop(Stack.java:46)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitReferenceExpression(JavaRecursiveElementVisitor.java:55)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.accept(PsiReferenceExpressionImpl.java:782)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:65)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:44)
	at com.intellij.psi.JavaElementVisitor.visitExpression(JavaElementVisitor.java:92)
	at com.intellij.psi.JavaElementVisitor.visitCallExpression(JavaElementVisitor.java:176)
	at com.intellij.psi.JavaElementVisitor.visitMethodCallExpression(JavaElementVisitor.java:172)
	at com.intellij.psi.impl.source.tree.java.PsiMethodCallExpressionImpl.accept(PsiMethodCallExpressionImpl.java:126)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:65)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:44)
	at com.intellij.psi.JavaElementVisitor.visitVariable(JavaElementVisitor.java:332)
	at com.intellij.psi.JavaElementVisitor.visitLocalVariable(JavaElementVisitor.java:164)
	at com.intellij.psi.impl.source.tree.java.PsiLocalVariableImpl.accept(PsiLocalVariableImpl.java:279)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:65)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:44)
	at com.intellij.psi.JavaElementVisitor.visitStatement(JavaElementVisitor.java:272)
	at com.intellij.psi.JavaElementVisitor.visitDeclarationStatement(JavaElementVisitor.java:68)
	at com.intellij.psi.impl.source.tree.java.PsiDeclarationStatementImpl.accept(PsiDeclarationStatementImpl.java:106)
	at com.intellij.psi.impl.source.tree.LazyParseablePsiElement.acceptChildren(LazyParseablePsiElement.java:100)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:44)
	at com.intellij.psi.JavaElementVisitor.visitCodeBlock(JavaElementVisitor.java:56)
	at com.intellij.psi.impl.source.tree.java.PsiCodeBlockImpl.accept(PsiCodeBlockImpl.java:212)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:65)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:44)
	at com.intellij.psi.JavaElementVisitor.visitStatement(JavaElementVisitor.java:272)
	at com.intellij.psi.JavaElementVisitor.visitTryStatement(JavaElementVisitor.java:304)
	at com.intellij.psi.impl.source.tree.java.PsiTryStatementImpl.accept(PsiTryStatementImpl.java:160)
	at com.intellij.psi.impl.source.tree.LazyParseablePsiElement.acceptChildren(LazyParseablePsiElement.java:100)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:44)
	at com.intellij.psi.JavaElementVisitor.visitCodeBlock(JavaElementVisitor.java:56)
	at com.intellij.psi.impl.source.tree.java.PsiCodeBlockImpl.accept(PsiCodeBlockImpl.java:212)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:185)
	at com.intellij.psi.impl.source.JavaStubPsiElement.acceptChildren(JavaStubPsiElement.java:113)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:44)
	at com.intellij.psi.JavaElementVisitor.visitMethod(JavaElementVisitor.java:168)
	at com.intellij.psi.impl.source.PsiMethodImpl.accept(PsiMethodImpl.java:289)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:185)
	at com.intellij.psi.impl.source.JavaStubPsiElement.acceptChildren(JavaStubPsiElement.java:113)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.internal.config.java.MicroProfileConfigASTValidator.visitClass(MicroProfileConfigASTValidator.java:106)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.internal.core.java.validators.MultiASTVisitor.visitClass(MultiASTVisitor.java:56)
	at com.intellij.psi.impl.source.PsiClassImpl.accept(PsiClassImpl.java:464)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:185)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:754)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:44)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:35)
	at com.intellij.psi.JavaElementVisitor.visitJavaFile(JavaElementVisitor.java:340)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.accept(PsiJavaFileBaseImpl.java:480)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.internal.core.java.validators.JavaASTDiagnosticsParticipant.collectDiagnosticsInFile(JavaASTDiagnosticsParticipant.java:51)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.internal.core.java.validators.JavaASTDiagnosticsParticipant.collectDiagnostics(JavaASTDiagnosticsParticipant.java:40)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManagerForJava.lambda$collectDiagnostics$18(PropertiesManagerForJava.java:317)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManagerForJava.lambda$collectDiagnostics$20(PropertiesManagerForJava.java:316)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:933)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:150)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManagerForJava.collectDiagnostics(PropertiesManagerForJava.java:304)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManagerForJava.diagnostics(PropertiesManagerForJava.java:290)
	at com.redhat.devtools.intellij.quarkus.lsp.QuarkusLanguageClient.lambda$getJavaDiagnostics$7(QuarkusLanguageClient.java:146)
	at com.redhat.devtools.intellij.quarkus.lsp.QuarkusLanguageClient.lambda$runAsBackground$2(QuarkusLanguageClient.java:120)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.redhat.devtools.intellij.quarkus.lsp.QuarkusLanguageClient.lambda$runAsBackground$3(QuarkusLanguageClient.java:118)
	at com.redhat.devtools.intellij.quarkus.lsp.QuarkusLanguageClient.lambda$runAsBackground$4(QuarkusLanguageClient.java:128)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by jeffmaury** [comment]
Very likely
