### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index -2 out of bounds for length -1

### ISSUE THREAD

**Issue by gastaldi** [redhat-developer/intellij-quarkus#587]
When the following class is opened in the IDE:
```java
package io.quarkus.it.rest;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.QueryParam;

@Path("/reflection")
public class ReflectionResource {

    @GET
    @Path("/simpleClassName")
    public String getSimpleClassName(@QueryParam("className") String className) {
        try {
            Class<?> clazz = Thread.currentThread().getContextClassLoader().loadClass(className);
            return clazz.getSimpleName();
        } catch (ClassNotFoundException e) {
            return "FAILED";
        }
    }

    @GET
    @Path("/lambda")
    public String getLambdaClassName() {
        try {
            ResourceLambda lambda = new ResourceLambda();
            Class<?> clazz = lambda.getLambdaFuncClass(5);
            return clazz.getSimpleName();
        } catch (Exception e) {
            return e.toString();
        }
    }

}

```

 the plugin fails with
```
Error while visiting node with com.redhat.devtools.intellij.lsp4mp4ij.psi.internal.config.java.MicroProfileConfigASTValidator

java.lang.IndexOutOfBoundsException: Index -2 out of bounds for length -1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at com.intellij.util.containers.Stack.peek(Stack.java:41)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:39)
	at com.intellij.psi.JavaElementVisitor.visitModifierList(JavaElementVisitor.java:180)
	at com.intellij.psi.impl.source.PsiModifierListImpl.accept(PsiModifierListImpl.java:323)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:185)
	at com.intellij.psi.impl.source.JavaStubPsiElement.acceptChildren(JavaStubPsiElement.java:113)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.internal.config.java.MicroProfileConfigASTValidator.visitClass(MicroProfileConfigASTValidator.java:106)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.internal.core.java.validators.MultiASTVisitor.visitClass(MultiASTVisitor.java:56)
	at com.intellij.psi.impl.source.PsiClassImpl.accept(PsiClassImpl.java:464)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:185)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:754)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:44)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:35)
	at com.intellij.psi.JavaElementVisitor.visitJavaFile(JavaElementVisitor.java:340)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.accept(PsiJavaFileBaseImpl.java:480)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.internal.core.java.validators.JavaASTDiagnosticsParticipant.collectDiagnosticsInFile(JavaASTDiagnosticsParticipant.java:51)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.internal.core.java.validators.JavaASTDiagnosticsParticipant.collectDiagnostics(JavaASTDiagnosticsParticipant.java:40)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManagerForJava.lambda$collectDiagnostics$18(PropertiesManagerForJava.java:317)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManagerForJava.lambda$collectDiagnostics$20(PropertiesManagerForJava.java:316)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:933)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:150)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManagerForJava.collectDiagnostics(PropertiesManagerForJava.java:304)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManagerForJava.diagnostics(PropertiesManagerForJava.java:290)
	at com.redhat.devtools.intellij.quarkus.lsp.QuarkusLanguageClient.lambda$getJavaDiagnostics$7(QuarkusLanguageClient.java:146)
	at com.redhat.devtools.intellij.quarkus.lsp.QuarkusLanguageClient.lambda$runAsBackground$2(QuarkusLanguageClient.java:120)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.redhat.devtools.intellij.quarkus.lsp.QuarkusLanguageClient.lambda$runAsBackground$3(QuarkusLanguageClient.java:118)
	at com.redhat.devtools.intellij.quarkus.lsp.QuarkusLanguageClient.lambda$runAsBackground$4(QuarkusLanguageClient.java:128)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by gastaldi** [comment]
Actually that's happening on any class, not just that one. I am not sure what's causing this

**Comment by jeffmaury** [comment]
Maybe fixed by 30628447fd1e6fb8f51a49422386f6adbd1fffb1

**Comment by gastaldi** [comment]
After restarting the IDE the error is gone, I'll close it and reopen if the error persists. When is the next release planned?

**Comment by jeffmaury** [comment]
In a few hours 🤕
