### ISSUE TITLE
Read access is allowed from inside read-action

### ISSUE THREAD

**Issue by MartinX3** [redhat-developer/intellij-quarkus#600]
```
Details: Current thread: Thread[JobScheduler FJ pool 7/7,4,main] 2062503672
Dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1879288328

java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1048)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findDirectory(FileManagerImpl.java:392)
	at com.intellij.psi.impl.PsiManagerImpl.findDirectory(PsiManagerImpl.java:168)
	at com.intellij.javascript.web.context.WebFrameworkContextImplKt.findWebFrameworkInContext(WebFrameworkContextImpl.kt:80)
	at com.intellij.javascript.web.WebFramework$Companion.forContext(WebFramework.kt:74)
	at com.intellij.javascript.web.lang.html.WebFrameworkHtmlLanguageSubstitutor.getLanguage(WebFrameworkHtmlLanguageSubstitutor.kt:12)
	at com.intellij.psi.LanguageSubstitutors.substituteLanguage(LanguageSubstitutors.java:58)
	at com.intellij.lang.LanguageUtil.getLanguageForPsi(LanguageUtil.java:48)
	at com.intellij.lang.LanguageUtil.getLanguageForPsi(LanguageUtil.java:30)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.LSPIJUtils.getFileLanguage(LSPIJUtils.java:44)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.LSPIJUtils.getDocumentLanguage(LSPIJUtils.java:137)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageServiceAccessor.getLSWrappers(LanguageServiceAccessor.java:341)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageServiceAccessor.getLanguageServers(LanguageServiceAccessor.java:577)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.operations.hover.LSPTextHover.lambda$initiateHoverRequest$5(LSPTextHover.java:214)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by MartinX3** [comment]
I hope 1.12.0 comes soon.
I'm getting spammed by this error.
