### ISSUE TITLE
IncorrectOperationException: Sorry but parent has already been disposed

### ISSUE THREAD

**Issue by gastaldi** [redhat-developer/intellij-quarkus#604]
This appeared when I opened a Quarkus project after restarting the IDE. Not reproducible all the time, but I think it would be nice to have it reported here

```java
com.intellij.util.IncorrectOperationException: Sorry but parent: org.jetbrains.idea.maven.MavenDisposable@4a1ee751 (class org.jetbrains.idea.maven.MavenDisposable) has already been disposed (see the cause for stacktrace) so the child: org.jetbrains.idea.maven.server.MavenServerManager$$Lambda$2885/0x0000000801c17440@607abbce (class org.jetbrains.idea.maven.server.MavenServerManager$$Lambda$2885/0x0000000801c17440) will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:53)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:118)
	at org.jetbrains.idea.maven.server.MavenServerManager.registerDisposable(MavenServerManager.java:208)
	at org.jetbrains.idea.maven.server.MavenServerManager.registerNewConnector(MavenServerManager.java:203)
	at org.jetbrains.idea.maven.server.MavenServerManager.doGetOrCreateConnector(MavenServerManager.java:164)
	at org.jetbrains.idea.maven.server.MavenServerManager.getConnector(MavenServerManager.java:135)
	at org.jetbrains.idea.maven.server.MavenServerManager$4.create(MavenServerManager.java:461)
	at org.jetbrains.idea.maven.server.MavenServerManager$4.create(MavenServerManager.java:443)
	at org.jetbrains.idea.maven.server.RemoteObjectWrapper.getOrCreateWrappee(RemoteObjectWrapper.java:42)
	at org.jetbrains.idea.maven.server.MavenEmbedderWrapper.lambda$resolve$11(MavenEmbedderWrapper.java:227)
	at org.jetbrains.idea.maven.server.RemoteObjectWrapper.performCancelable(RemoteObjectWrapper.java:90)
	at org.jetbrains.idea.maven.server.MavenEmbedderWrapper.resolve(MavenEmbedderWrapper.java:227)
	at com.redhat.devtools.intellij.quarkus.maven.MavenToolDelegate.ensureDownloaded(MavenToolDelegate.java:139)
	at com.redhat.devtools.intellij.quarkus.maven.MavenToolDelegate.getDeploymentFiles(MavenToolDelegate.java:112)
	at com.redhat.devtools.intellij.quarkus.maven.MavenToolDelegate.getDeploymentFiles(MavenToolDelegate.java:59)
	at com.redhat.devtools.intellij.quarkus.QuarkusModuleUtil.lambda$ensureQuarkusLibrary$0(QuarkusModuleUtil.java:97)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.lambda$updateModel$9(ModuleRootModificationUtil.java:147)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.modifyModel(ModuleRootModificationUtil.java:155)
	at com.intellij.openapi.roots.ModuleRootModificationUtil.updateModel(ModuleRootModificationUtil.java:146)
	at com.redhat.devtools.intellij.quarkus.QuarkusModuleUtil.ensureQuarkusLibrary(QuarkusModuleUtil.java:89)
	at com.redhat.devtools.intellij.quarkus.QuarkusPostStartupActivity.runActivity(QuarkusPostStartupActivity.java:24)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivity(StartupManagerImpl.kt:311)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:290)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration$default(StartupManagerImpl.kt:285)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1$1.run(StartupManagerImpl.kt:238)
	at com.intellij.openapi.project.DumbServiceImpl.runWithWaitForSmartModeDisabled(DumbServiceImpl.java:648)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1.accept(StartupManagerImpl.kt:237)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1.accept(StartupManagerImpl.kt:62)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:301)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:143)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:232)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:62)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$3$1.run(StartupManagerImpl.kt:180)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:365)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:343)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$3.run(StartupManagerImpl.kt:180)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by angelozerr** [comment]
We did alot of improvement to dispose some listener, I wonder if you have again this problem now?

In my case I cannot reproduce it. @gastaldi If you think it is fixed, please close the issue.

**Comment by gastaldi** [comment]
Closing for now
