### ISSUE TITLE
AssertionError: Command already registered 'qute.command.validation.template.status'

### ISSUE THREAD

**Issue by gastaldi** [redhat-developer/intellij-quarkus#617]
I am getting this error while building the Quarkus core with the Intellij Quarkus plugin 1.11.1.238 enabled:

```java
java.util.concurrent.CompletionException: java.lang.AssertionError: Command already registered 'qute.command.validation.template.status'
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1739)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.AssertionError: Command already registered 'qute.command.validation.template.status'
	at com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageServerWrapper.registerCommands(LanguageServerWrapper.java:795)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageServerWrapper.lambda$registerCapability$15(LanguageServerWrapper.java:736)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageServerWrapper.registerCapability(LanguageServerWrapper.java:715)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageClientImpl.lambda$registerCapability$2(LanguageClientImpl.java:85)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	... 6 more
```

**Comment by angelozerr** [comment]
I think this error occured when start/stop of LS was not managed correctly. Now we should not have this error.

I close this issue, @gastaldi please reopen it if you encounter again this issue.
