### ISSUE TITLE
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'file'

### ISSUE THREAD

**Issue by billoneil** [redhat-developer/intellij-quarkus#672]
I am receiving the following error fairly frequently when running the following versions

intellij-quarkus Version 1.13.1.283
IntelliJ: 2022.2.3

```Internal error: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'file' of com/intellij/openapi/vfs/VfsUtilCore.virtualToIoFile must not be null

java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'file' of com/intellij/openapi/vfs/VfsUtilCore.virtualToIoFile must not be null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at com.redhat.devtools.intellij.qute.lsp.QuteLanguageClient.runTask(QuteLanguageClient.java:131)
	at com.redhat.devtools.intellij.qute.lsp.QuteLanguageClient.access$000(QuteLanguageClient.java:64)
	at com.redhat.devtools.intellij.qute.lsp.QuteLanguageClient$1.run(QuteLanguageClient.java:106)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressInCurrentThread$10(CoreProgressManager.java:561)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressInCurrentThread(CoreProgressManager.java:561)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:381)
	at com.redhat.devtools.intellij.qute.lsp.QuteLanguageClient.lambda$runAsBackground$2(QuteLanguageClient.java:103)
	at com.redhat.devtools.intellij.qute.lsp.QuteLanguageClient.lambda$runAsBackground$3(QuteLanguageClient.java:117)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'file' of com/intellij/openapi/vfs/VfsUtilCore.virtualToIoFile must not be null
	at com.intellij.openapi.vfs.VfsUtilCore.$$$reportNull$$$0(VfsUtilCore.java)
	at com.intellij.openapi.vfs.VfsUtilCore.virtualToIoFile(VfsUtilCore.java)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.LSPIJUtils.toUri(LSPIJUtils.java:79)
	at com.redhat.devtools.intellij.qute.psi.utils.PsiQuteProjectUtils.getProjectInfo(PsiQuteProjectUtils.java:35)
	at com.redhat.devtools.intellij.qute.psi.QuteSupportForTemplate.getProjectInfo(QuteSupportForTemplate.java:111)
	at com.redhat.devtools.intellij.qute.lsp.QuteLanguageClient.lambda$getProjectInfo$5(QuteLanguageClient.java:142)
	at com.redhat.devtools.intellij.qute.lsp.QuteLanguageClient.runTask(QuteLanguageClient.java:127)
	... 23 more
```

**Comment by angelozerr** [comment]
Could you tell us which file are you opening please (java, application.properties, html files)?

Is it a file system?

Could you give us your full path please (have you some spaces in your file path)?

Thanks

**Comment by billoneil** [comment]
I no longer have this project set up to be able to give you more information. I'll close this out.
