### ISSUE TITLE
Error while editing a qute template

### ISSUE THREAD

**Issue by ia3andy** [redhat-developer/intellij-quarkus#674]
```
java.lang.Throwable: Too many element types registered. Out of (short) range. Most of element types (11164) were registered for 'Language: Qute_': QUTE_FILE, QuteElementType.#text, QuteElementType.#comment, QUTE-BLOCK, QUTE_FILE_DATA, QuteElementType.#insert, QuteElementType.#expression, QuteElementType.#include, QuteElementType.TEXT, QuteElementType.main.html, QuteElementType.TEXT, QuteElementType.#text, QuteElementType.#title, QuteElementTyp...
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.psi.tree.IElementType.<init>(IElementType.java:119)
	at com.intellij.psi.tree.IElementType.<init>(IElementType.java:97)
	at com.redhat.devtools.intellij.qute.lang.QuteElementType.<init>(QuteElementType.java:19)
	at com.redhat.devtools.intellij.qute.lang.QuteASTNode.<init>(QuteASTNode.java:32)
	at com.redhat.devtools.intellij.qute.lang.QuteASTNode.getNode(QuteASTNode.java:44)
	at com.redhat.devtools.intellij.qute.lang.QuteASTNode.<init>(QuteASTNode.java:34)
	at com.redhat.devtools.intellij.qute.lang.QuteASTNode.getNode(QuteASTNode.java:44)
	at com.redhat.devtools.intellij.qute.lang.QuteASTNode.<init>(QuteASTNode.java:34)
	at com.redhat.devtools.intellij.qute.lang.QuteASTNode.getNode(QuteASTNode.java:44)
	at com.redhat.devtools.intellij.qute.lang.QuteASTNode.<init>(QuteASTNode.java:34)
	at com.redhat.devtools.intellij.qute.lang.QuteASTNode.getNode(QuteASTNode.java:44)
	at com.redhat.devtools.intellij.qute.lang.QuteParser.lambda$parse$0(QuteParser.java:36)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.redhat.devtools.intellij.qute.lang.QuteParser.parse(QuteParser.java:36)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:58)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:53)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$2(LazyParseableElement.java:175)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:481)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:174)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:226)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:24)
	at com.intellij.psi.impl.BlockSupportImpl.isReplaceWholeNode(BlockSupportImpl.java:418)
	at com.intellij.psi.impl.BlockSupportImpl.mergeTrees(BlockSupportImpl.java:365)
	at com.intellij.psi.impl.BlockSupportImpl.makeFullParse(BlockSupportImpl.java:297)
	at com.intellij.psi.impl.BlockSupportImpl.reparse(BlockSupportImpl.java:92)
	at com.intellij.psi.impl.DocumentCommitThread.doCommit(DocumentCommitThread.java:269)
	at com.intellij.psi.impl.DocumentCommitThread.commitUnderProgress(DocumentCommitThread.java:136)
	at com.intellij.psi.impl.DocumentCommitThread.lambda$commitAsynchronously$0(DocumentCommitThread.java:79)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:161)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:118)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:407)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by ia3andy** [comment]
After the error the IDE becomes unusable

**Comment by angelozerr** [comment]
Could you add a little demo which reproduces the problem please.
