### ISSUE TITLE
NPE from MessageBusConnection.disconnect() on project loading

### ISSUE THREAD

**Issue by dcotfr** [redhat-developer/intellij-quarkus#693]
IntelliJ IDEA 2022.3 (Community Edition)
Build #IC-223.7571.182, built on November 29, 2022
Runtime version: 17.0.5+1-b653.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 20
Non-Bundled Plugins:
    net.sf.opk.avro-schema-support (213.2.1)
    com.redhat.devtools.intellij.telemetry (0.0.3.33)
    Docker (223.7571.175)
    com.redhat.devtools.intellij.quarkus (1.14.0.292)
    PlantUML integration (5.19)

Kotlin: 223-1.7.20-release-201-IJ7571.182

ExternalToolPass: 

com.intellij.diagnostic.PluginException: annotator: com.redhat.devtools.intellij.quarkus.lsp4ij.operations.codeactions.LSPCodeActionAnnotator@42a73200 (class com.redhat.devtools.intellij.quarkus.lsp4ij.operations.codeactions.LSPCodeActionAnnotator) [Plugin: com.redhat.devtools.intellij.quarkus]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.processError(ExternalToolPass.java:263)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.collectInformationWithProgress(ExternalToolPass.java:138)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:397)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:396)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:372)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:370)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.NullPointerException: Cannot invoke "com.intellij.util.messages.MessageBusConnection.disconnect()" because "this.messageBusConnection" is null
	at com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageServerWrapper.stop(LanguageServerWrapper.java:426)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageServerWrapper.start(LanguageServerWrapper.java:342)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageServerWrapper.getInitializedServer(LanguageServerWrapper.java:654)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageServerWrapper.getServerCapabilities(LanguageServerWrapper.java:687)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageServiceAccessor.lambda$getMatchingStartedWrappers$10(LanguageServiceAccessor.java:479)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageServiceAccessor.getMatchingStartedWrappers(LanguageServiceAccessor.java:480)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageServiceAccessor.getLSWrappers(LanguageServiceAccessor.java:301)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.operations.codeactions.LSPCodeActionAnnotator.doCollectInformation(LSPCodeActionAnnotator.java:96)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.operations.codeactions.LSPCodeActionAnnotator.collectInformation(LSPCodeActionAnnotator.java:82)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.operations.codeactions.LSPCodeActionAnnotator.collectInformation(LSPCodeActionAnnotator.java:57)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.collectInformationWithProgress(ExternalToolPass.java:135)
	... 21 more

**Comment by jeffmaury** [comment]
Fixed by 728c9662844066ee51a3195c1ea8020d34d21125
