### ISSUE TITLE
Internal error: java.lang.NullPointerException: Cannot invoke "String.length()" because "suffix" is null

### ISSUE THREAD

**Issue by mfortunat** [redhat-developer/intellij-quarkus#719]
Hi, 
This problem happens on average 2 or 3 times a day.
IntelliJ version is: 2022.3.1 - Build #IU-223.8214.52

Stack trace:
---
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "String.length()" because "suffix" is null
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
    at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
    at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
    at com.redhat.devtools.intellij.qute.lsp.QuteLanguageClient.runTask(QuteLanguageClient.java:131)
    at com.redhat.devtools.intellij.qute.lsp.QuteLanguageClient.access$000(QuteLanguageClient.java:64)
    at com.redhat.devtools.intellij.qute.lsp.QuteLanguageClient$1.run(QuteLanguageClient.java:106)
    at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:423)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressInCurrentThread$11(CoreProgressManager.java:542)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:589)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:588)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressInCurrentThread(CoreProgressManager.java:542)
    at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:365)
    at com.redhat.devtools.intellij.qute.lsp.QuteLanguageClient.lambda$runAsBackground$2(QuteLanguageClient.java:103)
    at com.redhat.devtools.intellij.qute.lsp.QuteLanguageClient.lambda$runAsBackground$3(QuteLanguageClient.java:117)
    at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
    at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "suffix" is null
    at java.base/java.lang.String.endsWith(String.java:2315)
    at com.redhat.devtools.intellij.qute.psi.utils.AnnotationUtils.isMatchAnnotation(AnnotationUtils.java:85)
    at com.redhat.devtools.intellij.qute.psi.internal.java.AbstractQuteTemplateLinkCollector.visitClass(AbstractQuteTemplateLinkCollector.java:139)
    at com.intellij.psi.impl.source.PsiClassImpl.accept(PsiClassImpl.java:464)
    at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:185)
    at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:754)
    at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:44)
    at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:51)
    at com.intellij.psi.JavaElementVisitor.visitJavaFile(JavaElementVisitor.java:209)
    at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.accept(PsiJavaFileBaseImpl.java:478)
    at com.redhat.devtools.intellij.qute.psi.internal.java.QuarkusIntegrationForQute.diagnostics(QuarkusIntegrationForQute.java:51)
    at com.redhat.devtools.intellij.qute.psi.QuteSupportForJava.diagnostics(QuteSupportForJava.java:86)
    at com.redhat.devtools.intellij.qute.lsp.QuteLanguageClient.lambda$getJavaDiagnostics$15(QuteLanguageClient.java:178)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:873)
    at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
    at com.redhat.devtools.intellij.qute.lsp.QuteLanguageClient.lambda$getJavaDiagnostics$16(QuteLanguageClient.java:178)
    at com.redhat.devtools.intellij.qute.lsp.QuteLanguageClient.runTask(QuteLanguageClient.java:127)
    ... 23 more

**Comment by angelozerr** [comment]
Could you share please your project and which template file you try to open it please.

**Comment by mfortunat** [comment]
Hi, 

With the versions of IntelliJ (2023.1) and Quarkus Tools (1.17.0.338), the problem has disappeared.
You can close this ticket.
I will open a new one, just in case.

Thanks

**Comment by angelozerr** [comment]
@mfortunat thanks for your feedback.
