### ISSUE TITLE
Internal error with IDE stuck for seconds

### ISSUE THREAD

**Issue by cleciusjm** [redhat-developer/intellij-quarkus#720]
related to #748

My Intellij stuck for some seconds randomly, every time this stacktrace appears:

```
Internal error: java.lang.IllegalStateException: Dynamic command registration failed! Server not yet initialized?

java.util.concurrent.CompletionException: java.lang.IllegalStateException: Dynamic command registration failed! Server not yet initialized?
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.IllegalStateException: Dynamic command registration failed! Server not yet initialized?
	at com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageServerWrapper.registerCommands(LanguageServerWrapper.java:815)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageServerWrapper.lambda$registerCapability$16(LanguageServerWrapper.java:748)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageServerWrapper.registerCapability(LanguageServerWrapper.java:727)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageClientImpl.lambda$registerCapability$2(LanguageClientImpl.java:85)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	... 6 more

```

I'm using:

```
IntelliJ IDEA 2022.3.1 (Ultimate Edition)
Build #IU-223.8214.52, built on December 20, 2022
Runtime version: 17.0.5+1-b653.23 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.0.15-1-manjaro
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.markskelton.one-dark-theme (5.7.2)
    com.redhat.devtools.intellij.telemetry (0.0.3.33)
    com.redhat.devtools.intellij.quarkus (1.15.0.308)

Kotlin: 223-1.7.21-release-272-IJ8214.52
Current Desktop: GNOME
```

**Comment by cleciusjm** [comment]
Another fail that occurs more often (taken from journalctl):

```
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]: 2022-12-30 10:31:48,958 [2176732]   WARN - com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageServerWrapper - null
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]: java.util.concurrent.TimeoutException
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageServerWrapper.supportsWorkspaceFolderCapability(LanguageServerWrapper.java:538)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageServerWrapper.canOperate(LanguageServerWrapper.java:865)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageServiceAccessor.lambda$getLSWrappers$6(LanguageServiceAccessor.java:372)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at java.base/java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1728)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageServiceAccessor.getLSWrappers(LanguageServiceAccessor.java:371)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at com.redhat.devtools.intellij.quarkus.lsp4ij.LanguageServiceAccessor.getLanguageServers(LanguageServiceAccessor.java:577)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at com.redhat.devtools.intellij.quarkus.lsp4ij.operations.codelens.LSPCodelensInlayProvider$1.collect(LSPCodelensInlayProvider.java:71)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at com.intellij.codeInsight.hints.CollectorWithSettings.collectHints(InlayHintsUtils.kt:92)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at com.intellij.codeInsight.hints.InlayHintsPass.doCollectInformation$lambda$0(InlayHintsPass.kt:47)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:589)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:588)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:86)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
dez 30 10:31:48 cj-manjaro jetbrains-idea.desktop[15987]:         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

**Comment by adietish** [comment]
Ho @cleciusjm

In #748 we fixed an issue that this related to yours. It will be available in the next release. I'd then love your feedback if you still experience this problem. Thanks!

**Comment by angelozerr** [comment]
> Another fail that occurs more often (taken from journalctl):

If you ar eediting JAX-RS classes with @Path, I think it should be fixed with https://github.com/redhat-developer/intellij-quarkus/pull/793

**Comment by angelozerr** [comment]
Performance and freeze problem should be fixed with https://github.com/redhat-developer/intellij-quarkus/pull/849

Please repoen if you find some again troubles
