### ISSUE TITLE
CannotReadException in IntelliJ IDEA 2022.3.1 (Ultimate Edition)

### ISSUE THREAD

**Issue by adben** [redhat-developer/intellij-quarkus#729]
At an irregular rate, this exception appears when triggering different actions related to a Quarkus project 
```java
Internal error: com.intellij.openapi.application.ReadAction$CannotReadException

java.util.concurrent.CompletionException: com.intellij.openapi.application.ReadAction$CannotReadException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at com.redhat.devtools.intellij.quarkus.lsp.QuarkusLanguageClient.lambda$runAsBackground$2(QuarkusLanguageClient.java:124)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:589)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:588)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.redhat.devtools.intellij.quarkus.lsp.QuarkusLanguageClient.lambda$runAsBackground$3(QuarkusLanguageClient.java:120)
	at com.redhat.devtools.intellij.quarkus.lsp.QuarkusLanguageClient.lambda$runAsBackground$4(QuarkusLanguageClient.java:130)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: com.intellij.openapi.application.ReadAction$CannotReadException
	at org.asciidoc.intellij.threading.AsciiDocProcessUtil.lambda$runInReadActionWithWriteActionPriority$0(AsciiDocProcessUtil.java:34)
	at org.asciidoc.intellij.threading.AsciiDocProcessUtil.retryable(AsciiDocProcessUtil.java:70)
	at org.asciidoc.intellij.threading.AsciiDocProcessUtil.runInReadActionWithWriteActionPriority(AsciiDocProcessUtil.java:30)
	at org.asciidoc.intellij.findUsages.AsciiDocJavaReferencesSearch.processQuery(AsciiDocJavaReferencesSearch.java:41)
	at org.asciidoc.intellij.findUsages.AsciiDocJavaReferencesSearch.processQuery(AsciiDocJavaReferencesSearch.java:30)
	at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:76)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:30)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:88)
	at com.intellij.util.AbstractQuery.delegateProcessResults(AbstractQuery.java:105)
	at com.intellij.util.MergeQuery.processResults(MergeQuery.java:22)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:88)
	at com.intellij.util.AbstractQuery.delegateProcessResults(AbstractQuery.java:105)
	at com.intellij.util.UniqueResultsQuery.processResults(UniqueResultsQuery.java:37)
	at com.intellij.util.AbstractQuery.doProcessResults(AbstractQuery.java:88)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:80)
	at com.intellij.util.AbstractQuery.findAll(AbstractQuery.java:25)
	at com.intellij.util.Query.iterator(Query.java:127)
	at com.intellij.util.AbstractQuery.iterator(AbstractQuery.java:36)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.internal.restclient.java.MicroProfileRestClientDiagnosticsParticipant.validateInterfaceType(MicroProfileRestClientDiagnosticsParticipant.java:201)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.internal.restclient.java.MicroProfileRestClientDiagnosticsParticipant.collectDiagnostics(MicroProfileRestClientDiagnosticsParticipant.java:100)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.internal.restclient.java.MicroProfileRestClientDiagnosticsParticipant.collectDiagnostics(MicroProfileRestClientDiagnosticsParticipant.java:90)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManagerForJava.lambda$collectDiagnostics$18(PropertiesManagerForJava.java:324)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManagerForJava.lambda$collectDiagnostics$20(PropertiesManagerForJava.java:323)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:156)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:873)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:149)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManagerForJava.collectDiagnostics(PropertiesManagerForJava.java:311)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManagerForJava.diagnostics(PropertiesManagerForJava.java:297)
	at com.redhat.devtools.intellij.quarkus.lsp.QuarkusLanguageClient.lambda$getJavaDiagnostics$7(QuarkusLanguageClient.java:148)
	at com.redhat.devtools.intellij.quarkus.lsp.QuarkusLanguageClient.lambda$runAsBackground$2(QuarkusLanguageClient.java:122)
	... 16 more
```

more info about the current IntelliJ context:
IntelliJ IDEA 2022.3.1 (Ultimate Edition)
Build #IU-223.8214.52, built on December 20, 2022
You have a perpetual fallback license for this version.
Subscription is active until January 7, 2024.
Runtime version: 17.0.5+1-b653.23 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.1
GC: G1 Young Generation, G1 Old Generation
Memory: 6000M
Cores: 10
Metal Rendering is ON
Registry:
    analyze.exceptions.on.the.fly=true
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.minimap.enabled=true

Non-Bundled Plugins:
    com.paperetto.dash (3.3)
    org.rust.lang (0.4.186.5143-223)
    com.nasller.CodeGlancePro (1.5.9)
    com.intellij.plugins.macoskeymap (223.7571.117)
    com.jetbrains.edu (2022.12-2022.3-161)
    bundled-intellij-idea-help (223.8214.52)
    Rider UI Theme Pack (0.11.0)
    monokai-pro (1.10)
    com.intellij.drools (223.8214.16)
    org.jetbrains.plugins.go-template (223.7571.203)
    VisualVMLauncher (1.21.211.6085.0)
    com.intellij.guice (223.7571.182)
    com.jetbrains.jax.ws (223.8214.16)
    com.redhat.devtools.intellij.telemetry (0.0.3.33)
    com.intellij.properties.bundle.editor (223.7571.203)
    CMD Support (1.0.5)
    com.arcticicestudio.nord.jetbrains (0.13.0)
    org.jetbrains.plugins.go (223.8214.52)
    com.intellij.aqua.selenium (223.8214.16)
    com.intellij.selenium (223.7571.117)
    com.redhat.devtools.intellij.quarkus (1.15.0.308)
    com.intellij.jboss.arquillian (223.7571.182)
    com.intellij.javaee.ejb (223.7571.182)
    com.intellij.kubernetes (223.8214.33)
    com.intellij.nativeDebug (223.8214.16)
    org.intellij.scala (2022.3.15)
    com.jetbrains.lang.ejs (223.7571.117)
    org.asciidoctor.intellij.asciidoc (0.38.4)
    Pythonid (223.8214.52)
    com.intellij.bigdatatools (223.8214.65)
    org.sonarlint.idea (7.3.0.59206)
    mobi.hsz.idea.gitignore (4.4.4)
    net.ashald.envfile (3.4.1)
    Osmorc (223.7571.182)
    com.pixelperfect.gitlab-ci (2023.1.2)

Kotlin: 223-1.7.21-release-272-IJ8214.52

**Comment by angelozerr** [comment]
I close this issue since it should be fixed with https://github.com/redhat-developer/intellij-quarkus/pull/746

@adben if you have again the problem, please reopen it. Thanks.
