### ISSUE TITLE
java.lang.IndexOutOfBoundsException when trying to "insert @RestClient"

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-quarkus#764]
**Steps:**
1. EXEC: have git@github.com:adietish/code-with-quarkus.git cloned and imported into IJ
2. EXEC: open `ExtenstionsResource.java` in an editor
3. EXEC: put cursor into `extensionsService` and activate the suggestions (press Alt + Return)
4. ASSERT: "Insert @RestClient" is suggested
<img width="538" alt="image" src="https://user-images.githubusercontent.com/25126/228841622-d9cd51af-ea7b-4a56-bd70-329bd7ed82ce.png">
6. EXEC: select it

**Result:**
"@RestClient" is not inserted, fatal IDE error is displayed with the following stacktrace:
```
java.lang.IndexOutOfBoundsException: Wrong line: 22. Available lines count: 21
	at com.intellij.openapi.editor.impl.LineSet.checkLineIndex(LineSet.java:200)
	at com.intellij.openapi.editor.impl.LineSet.getLineStart(LineSet.java:181)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineStartOffset(DocumentImpl.java:1027)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.LSPIJUtils.toOffset(LSPIJUtils.java:120)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.LSPIJUtils.applyWorkspaceEdit(LSPIJUtils.java:219)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.LSPIJUtils.applyWorkspaceEdit(LSPIJUtils.java:157)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.operations.codeactions.LSPCodeActionIntentionAction.apply(LSPCodeActionIntentionAction.java:96)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.operations.codeactions.LSPCodeActionIntentionAction.invoke(LSPCodeActionIntentionAction.java:84)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.lambda$invoke$0(IntentionActionWithTextCaching.java:223)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:194)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.invoke(IntentionActionWithTextCaching.java:223)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$invokeIntention$8(ShowIntentionActionsHandler.java:273)
	at com.intellij.openapi.application.WriteAction.lambda$run$1(WriteAction.java:87)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:946)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:972)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:86)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.invokeIntention(ShowIntentionActionsHandler.java:273)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$chooseActionAndInvoke$7(ShowIntentionActionsHandler.java:250)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:164)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:150)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:249)
	at com.intellij.codeInsight.intention.impl.IntentionListStep.chooseActionAndInvoke(IntentionListStep.java:137)
	at com.intellij.codeInsight.intention.impl.IntentionListStep.lambda$applyAction$0(IntentionListStep.java:129)
	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$17(AbstractPopup.java:1618)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$3(FocusManagerImpl.java:172)
	at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:33)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.kt:187)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.kt:153)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:168)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:162)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1616)
	at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:165)
	at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:391)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:127)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:159)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:264)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:252)
	at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:273)
	at com.intellij.ui.popup.list.ListPopupImpl.disposePopup(ListPopupImpl.java:485)
	at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:512)
	at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:479)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:426)
	at com.intellij.ui.popup.list.ListPopupImpl$1.actionPerformed(ListPopupImpl.java:281)
	at com.intellij.ui.popup.WizardPopup.proceedKeyEvent(WizardPopup.java:400)
	at com.intellij.ui.popup.WizardPopup.dispatch(WizardPopup.java:372)
	at com.intellij.ui.popup.PopupDispatcher.dispatchKeyEvent(PopupDispatcher.java:115)
	at com.intellij.ui.popup.PopupDispatcher.dispatch(PopupDispatcher.java:157)
	at com.intellij.ide.IdePopupManager.dispatch(IdePopupManager.java:107)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:546)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by adietish** [comment]
What happens here is that the change that is presented to the code is the whole document after items were inserted:

`LSPIJUtils#applyWorkspaceEdit`:
```java
    private static void applyWorkspaceEdit(Document document, List<TextEdit> edits) {
        for(TextEdit edit : edits) {
            if (edit.getRange() != null) {
                String text = edit.getNewText();
                int start = toOffset(edit.getRange().getStart(), document);
                int end = toOffset(edit.getRange().getEnd(), document);

```

* document.getText():
```
package org.acme.rest.client;
import org.jboss.resteasy.annotations.jaxrs.PathParam;
import javax.inject.Inject;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import java.util.Set;
@Path("/extension")
public class ExtensionsResource {
    @Inject
    ExtensionsService extensionsService;
    @GET
    @Path("/id/{id}")
    public Set<Extension> id(@PathParam String id) {
        return extensionsService.getById(id);
    }
}
```
* text:
```java
package org.acme.rest.client;
--->import org.eclipse.microprofile.rest.client.inject.RestClient;
import org.jboss.resteasy.annotations.jaxrs.PathParam;
import javax.inject.Inject;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import java.util.Set;
@Path("/extension")
public class ExtensionsResource {
---> @RestClient
    @Inject
    ExtensionsService extensionsService;
    @GET
    @Path("/id/{id}")
    public Set<Extension> id(@PathParam String id) {
        return extensionsService.getById(id);
    }
}
```

**Comment by adietish** [comment]
There's an underlying bug at work here. If I monitor the log messages that are spit out by the LS in intellij-quarkus I see it out-of-sync. Here's an example:

The cursor is at line 14 in the editor, the editor highlights the instance variable type:
![image](https://user-images.githubusercontent.com/25126/230385768-8f870be8-74ce-4ed6-962d-d2e1dd3e87e0.png)

In the log, the LS thinks that he's at line 13:
```
[t=1680785665942] LSP4E to qute:
{"jsonrpc":"2.0","id":"34","method":"textDocument/documentHighlight","params":{"textDocument":{"uri":"file:///Users/andredietisheim/git/code-with-quarkus/src/main/java/org/acme/rest/client/ExtensionsResource.java"},"position":{"line":13,"character":20}}}
[t=1680785665943] qute to LSP4E:
{"jsonrpc":"2.0","id":"34","result":null}
```

**Comment by jeffmaury** [comment]
Lines in LSP are 0 based and 1 based in the editor asking @angelozerr for confirmation

**Comment by adietish** [comment]
@jeffmaury ok, thanks. Will dig further, but I thought that I saw discrepancies which were not just by 1 line.

**Comment by adietish** [comment]
There's one more problem here: If you have the annotation inserted and Undo (or remove it manually) right afterwards, the code action is not suggested any longer.

**Comment by angelozerr** [comment]
Except your last comment I have the impression that problem comes from when there are several textedit

**Comment by jeffmaury** [comment]
> Except your last comment I have the impression that problem comes from when there are several textedit

No LSP4MP code actions implementation is generating the whole document and returning it as a single textedit but the range is currently computed on the new document and not on the original document that's the issue

**Comment by angelozerr** [comment]
> No LSP4MP code actions implementation is generating the whole document and returning it as a single textedit but the range is currently computed on the new document and not on the original document that's the issue

Ok after debugging I understand more the problem. The problem comes from

https://github.com/redhat-developer/intellij-quarkus/blob/025e7dcae412f003bb9f077e0f80b61e8f68c962/src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/java/corrections/proposal/ASTRewriteCorrectionProposal.java#L48

`sourceCU.getViewProvider().getDocument()` and `document `are the same instance, it means that you update the origin document, is not dangerous to do that?

**Comment by jeffmaury** [comment]
Non you probably missed one point

**Comment by adietish** [comment]
@angelozerr with #781 this is fixed for me. There's still an issue where the suggestion wont appear if you remove the annotation once you applied it. I'll file a different issue for this.
Closing this issue.
