### ISSUE TITLE
New project can be created with blank "Class name" and "Path" fields

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-quarkus#79]
- new project can be created with blank "Class name" and "Path" fields, which leads to the following exception (by the way - I also think all required field should be marked with an asterisk):

```
com.intellij.util.io.HttpRequests$HttpStatusException: Request failed with status code 400. Status=400, Url=https://code.quarkus.io/api/download?p&a=code-with-quarkus&b=MAVEN&c&v=1.0.0-SNAPSHOT&g=org.acme
	at com.intellij.util.io.HttpRequests.throwHttpStatusError(HttpRequests.java:643)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:624)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:375)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:384)
	at com.redhat.devtools.intellij.quarkus.module.QuarkusModuleBuilder.lambda$null$2(QuarkusModuleBuilder.java:142)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:349)
	at com.redhat.devtools.intellij.quarkus.module.QuarkusModuleBuilder.lambda$processDownload$3(QuarkusModuleBuilder.java:141)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by zcervink** [comment]
Update - after repeatedly deleting and creating new projects with blank "Class name" and "Path" fields, sometimes happens that new project is created with the default class name (org.acme.ExampleResource) and default Path (/hello)
