### ISSUE TITLE
Cannot compute MicroProfile properties for the Java element 'PsiClass:CacheConfig'.

### ISSUE THREAD

**Issue by gastaldi** [redhat-developer/intellij-quarkus#801]
The following error appears when I edit an application.properties (https://github.com/quarkusio/registry.quarkus.io/blob/main/src/main/resources/application.properties specifically).

I am using Quarkus Tools 1.17.1.346

```java
Cannot compute MicroProfile properties for the Java element 'PsiClass:CacheConfig'.

java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:152)
	at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:214)
	at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:214)
	at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.processConfigMapping(QuarkusConfigMappingProvider.java:120)
	at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.processAnnotation(QuarkusConfigMappingProvider.java:90)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.AbstractAnnotationTypeReferencePropertiesProvider.processAnnotation(AbstractAnnotationTypeReferencePropertiesProvider.java:58)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.AbstractAnnotationTypeReferencePropertiesProvider.collectProperties(AbstractAnnotationTypeReferencePropertiesProvider.java:48)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManager.collectProperties(PropertiesManager.java:126)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManager.lambda$getMicroProfileProjectInfo$1(PropertiesManager.java:103)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManager.lambda$getMicroProfileProjectInfo$2(PropertiesManager.java:103)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:156)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:891)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:69)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:149)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:100)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:87)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:78)
	at com.redhat.devtools.intellij.quarkus.lsp.QuarkusLanguageClient.lambda$getProjectInfo$2(QuarkusLanguageClient.java:112)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.IndexAwareLanguageClient.runTask(IndexAwareLanguageClient.java:97)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.IndexAwareLanguageClient$1.run(IndexAwareLanguageClient.java:76)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressInCurrentThread$11(CoreProgressManager.java:557)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressInCurrentThread(CoreProgressManager.java:557)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:363)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.IndexAwareLanguageClient.lambda$runAsBackground$0(IndexAwareLanguageClient.java:73)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.IndexAwareLanguageClient.lambda$runAsBackground$1(IndexAwareLanguageClient.java:87)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by angelozerr** [comment]
@adietish do you want to fix this issue coming from lsp4mp xhich should be easy to fix it. It seems that the java type is OptionalInt without generic and we try to get the generic.

If yoy want to fix it pnease write à test too with this usecase. I think it can be à good start to contribue to lsp4mp for IJ

**Comment by adietish** [comment]
I can reproduce this. Looking into it.

**Comment by angelozerr** [comment]
@gastaldi the problem occurs when your Java field is OprionalInt, OptionalBoolean, etc

```
@ConfigItem
public OptionalInt bar;
```

@adietish is working on this fix.

**Comment by adietish** [comment]
The very same problem exists for jbosstools-quarkus. I have a fix and tests, I believe. Stressing it.
