### ISSUE TITLE
Make the plugin build against version 2020.1 

### ISSUE THREAD

**Issue by koentsje** [redhat-developer/intellij-quarkus#83]
The plugin currently does not compile against the most recent versions of Idea
- org.jetbrains.intellij plugin version 0.4.19
- Idea version IC-2020.1
This is because of removed APIs

**Comment by zcervink** [comment]
@koentsje can you confirm, that this issue shows this message on startup of IntelliJ (or I have another issue):

```
Plugin 'com.redhat.devtools.intellij.quarkus' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.UnsupportedClassVersionError: com/redhat/devtools/intellij/quarkus/lsp/QuarkusLSPInitializer has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 55.0
    at java.base/java.lang.ClassLoader.defineClass1(Native Method)
    at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
    at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:380)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:376)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:340)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:259)
    at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:205)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:113)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    at java.base/java.lang.Class.forName0(Native Method)
    at java.base/java.lang.Class.forName(Class.java:398)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:288)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:194)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:157)
    at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt:93)
    at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
    at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
    at com.intellij.idea.ApplicationLoader$initApplication$2.accept(ApplicationLoader.kt:379)
    at com.intellij.idea.ApplicationLoader$initApplication$2.accept(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
    at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by zcervink** [comment]
> @koentsje can you confirm, that this issue shows this message on startup of IntelliJ (or I have another issue?):
> 
> ```
> Plugin 'com.redhat.devtools.intellij.quarkus' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.
> 
> java.lang.UnsupportedClassVersionError: com/redhat/devtools/intellij/quarkus/lsp/QuarkusLSPInitializer has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 55.0
>     at java.base/java.lang.ClassLoader.defineClass1(Native Method)
>     at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
>     at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
>     at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:380)
>     at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:376)
>     at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:340)
>     at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:259)
>     at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:205)
>     at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:113)
>     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
>     at java.base/java.lang.Class.forName0(Native Method)
>     at java.base/java.lang.Class.forName(Class.java:398)
>     at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:288)
>     at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:194)
>     at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:157)
>     at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt:93)
>     at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt)
>     at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
>     at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
>     at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
>     at com.intellij.idea.ApplicationLoader$initApplication$2.accept(ApplicationLoader.kt:379)
>     at com.intellij.idea.ApplicationLoader$initApplication$2.accept(ApplicationLoader.kt)
>     at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
>     at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
>     at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
>     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
>     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>     at java.base/java.lang.Thread.run(Thread.java:834)
> ```

@koentsje sorry for my post above - that exception shows when you compile using Java 14 which I have accidentally downloaded.

**Comment by koentsje** [comment]
yes, I ran a few times against that one as well ;-)
