### ISSUE TITLE
Logged error when LSP console is activated and project is closed

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/intellij-quarkus#862]
Activate the LSP console and close the project, you will see this error:

```
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.codeInsight.daemon.impl.EditorTracker because container is already disposed: Project(name=untitled2, containerState=DISPOSE_COMPLETED, componentStore=C:\Users\azerr\IdeaProjects\untitled2) (disposed)
	at com.intellij.serviceContainer.ComponentManagerImpl.throwContainerIsAlreadyDisposed(ComponentManagerImpl.kt:491)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:467)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:440)
	at com.intellij.codeInsight.daemon.impl.EditorTracker.getInstance(EditorTracker.java:59)
	at com.intellij.codeInsight.daemon.impl.EditorTracker$MyAppLevelEditorFactoryListener.editorReleased(EditorTracker.java:75)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.lambda$releaseEditor$1(EditorFactoryImpl.java:217)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.java:33)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.java:49)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.releaseEditor(EditorFactoryImpl.java:217)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.validateEditorsAreReleased(EditorFactoryImpl.java:92)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl$1.lambda$projectClosed$0(EditorFactoryImpl.java:64)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2023-05-17 16:27:29,037 [2701347]  ERROR - nsions.impl.ExtensionPointImpl - IntelliJ IDEA 2020.3  Build #IC-203.5981.155 
2023-05-17 16:27:29,037 [2701347]  ERROR - nsions.impl.ExtensionPointImpl - JDK: 11.0.9; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2023-05-17 16:27:29,037 [2701347]  ERROR - nsions.impl.ExtensionPointImpl - OS: Windows 10 
2023-05-17 16:27:29,037 [2701347]  ERROR - nsions.impl.ExtensionPointImpl - Last Action: CloseProject 
2023-05-17 16:27:29,038 [2701348]  ERROR - pplication.impl.LaterInvocator - Editor of class com.intellij.openapi.editor.impl.EditorImpl hasn't been released: 
com.intellij.openapi.util.TraceableDisposable.ObjectNotDisposedException: See stack trace responsible for creation of unreleased object below 
	at com.intellij.openapi.editor.impl.EditorImpl.<init>(EditorImpl.java:150)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:197)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createViewer(EditorFactoryImpl.java:167)
	at com.intellij.execution.impl.ConsoleViewUtil.setupConsoleEditor(ConsoleViewUtil.java:55)
	at com.intellij.execution.impl.ConsoleViewImpl.doCreateConsoleEditor(ConsoleViewImpl.java:952)
	at com.intellij.execution.impl.ConsoleViewImpl.lambda$createConsoleEditor$11(ConsoleViewImpl.java:930)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:885)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.execution.impl.ConsoleViewImpl.createConsoleEditor(ConsoleViewImpl.java:929)
	at com.intellij.execution.impl.ConsoleViewImpl.initConsoleEditor(ConsoleViewImpl.java:420)
	at com.intellij.execution.impl.ConsoleViewImpl.getComponent(ConsoleViewImpl.java:388)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.console.LSPConsoleToolWindowPanel$ConsoleOrErrorPanel.<init>(LSPConsoleToolWindowPanel.java:117)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.console.LSPConsoleToolWindowPanel$ConsolesPanel.create(LSPConsoleToolWindowPanel.java:93)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.console.LSPConsoleToolWindowPanel$ConsolesPanel.create(LSPConsoleToolWindowPanel.java:81)
	at com.intellij.ui.CardLayoutPanel.createValue(CardLayoutPanel.java:81)
	at com.intellij.ui.CardLayoutPanel.select(CardLayoutPanel.java:109)
	at com.intellij.ui.CardLayoutPanel.select(CardLayoutPanel.java:94)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.console.LSPConsoleToolWindowPanel.selectConsole(LSPConsoleToolWindowPanel.java:75)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.console.explorer.LanguageServerExplorer.onLanguageServerSelected(LanguageServerExplorer.java:57)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.console.explorer.LanguageServerExplorer.lambda$buildTree$1(LanguageServerExplorer.java:83)
	at java.desktop/javax.swing.JTree.fireValueChanged(JTree.java:2967)
	at java.desktop/javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3456)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:641)
	at com.intellij.ui.treeStructure.Tree$MySelectionModel.fireValueChanged(Tree.java:618)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1111)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:297)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:191)
	at java.desktop/javax.swing.JTree.setSelectionPath(JTree.java:1656)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.console.explorer.LanguageServerExplorer.selectAndExpand(LanguageServerExplorer.java:118)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.console.explorer.LanguageServerExplorerLifecycleListener.showMessage(LanguageServerExplorerLifecycleListener.java:268)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.console.explorer.LanguageServerExplorerLifecycleListener.lambda$handleLSPMessage$3(LanguageServerExplorerLifecycleListener.java:157)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2023-05-17 16:27:29,039 [2701349]  ERROR - pplication.impl.LaterInvocator - IntelliJ IDEA 2020.3  Build #IC-203.5981.155 
2023-05-17 16:27:29,039 [2701349]  ERROR - pplication.impl.LaterInvocator - JDK: 11.0.9; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2023-05-17 16:27:29,039 [2701349]  ERROR - pplication.impl.LaterInvocator - OS: Windows 10 
2023-05-17 16:27:29,040 [2701350]  ERROR - pplication.impl.LaterInvocator - Last Action: CloseProject 

```

It is because when we close project,language server is stopped and report a log that it tries to be loggued in the console. I tried to check the isDispose (from project, from UI, from listener) without success.

**Comment by adietish** [comment]
I cannot replicate this. Maybe this only happens on Windows (and Linux?). I am running a Mac.

**Comment by fbricon** [comment]
it might also depend on the IDEA version

**Comment by adietish** [comment]
After having closed IDEA I found the following in my log:
```
java.lang.RuntimeException: Memory leak detected: 'com.redhat.devtools.intellij.lsp4ij.console.LSPConsoleView[,0,0,1153x302,invalid,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]' of class com.redhat.devtools.intellij.lsp4ij.console.LSPConsoleView is registered in Disposer but wasn't disposed.
Register it with a proper parentDisposable or ensure that it's always disposed by direct Disposer.dispose call.
See https://jetbrains.org/intellij/sdk/docs/basics/disposers.html for more details.
The corresponding Disposer.register() stacktrace is shown as the cause:

	at com.intellij.openapi.util.ObjectTree.assertIsEmpty(ObjectTree.java:233)
	at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:233)
	at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:228)
	at com.intellij.openapi.application.impl.ApplicationImpl.disposeContainer(ApplicationImpl.java:228)
	at com.intellij.openapi.application.impl.ApplicationImpl.disposeSelf(ApplicationImpl.java:245)
	at com.intellij.openapi.application.impl.ApplicationImpl.doExit(ApplicationImpl.java:669)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:622)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:611)
	at com.intellij.openapi.application.ex.ApplicationEx.exit(ApplicationEx.java:75)
	at com.intellij.ui.mac.MacOSApplicationProvider$Worker.lambda$initMacApplication$3(MacOSApplicationProvider.java:80)
	at com.intellij.ui.mac.MacOSApplicationProvider$Worker.lambda$submit$8(MacOSApplicationProvider.java:174)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.Throwable
	at com.intellij.openapi.util.ObjectNode.<init>(ObjectNode.java:31)
	at com.intellij.openapi.util.ObjectTree.createNodeFor(ObjectTree.java:100)
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:61)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:118)
	at com.intellij.util.Alarm.<init>(Alarm.java:144)
	at com.intellij.execution.impl.ConsoleViewImpl.<init>(ConsoleViewImpl.java:96)
	at com.intellij.execution.impl.ConsoleViewImpl.<init>(ConsoleViewImpl.java:157)
	at com.redhat.devtools.intellij.lsp4ij.console.LSPConsoleView.<init>(LSPConsoleView.java:47)
	at com.redhat.devtools.intellij.lsp4ij.console.LSPTextConsoleBuilderImpl.createConsole(LSPTextConsoleBuilderImpl.java:39)
	at com.intellij.execution.filters.TextConsoleBuilderImpl.getConsole(TextConsoleBuilderImpl.java:31)
	at com.redhat.devtools.intellij.lsp4ij.console.LSPConsoleToolWindowPanel.createConsoleView(LSPConsoleToolWindowPanel.java:227)
	at com.redhat.devtools.intellij.lsp4ij.console.LSPConsoleToolWindowPanel$ConsoleContentPanel.<init>(LSPConsoleToolWindowPanel.java:144)
	at com.redhat.devtools.intellij.lsp4ij.console.LSPConsoleToolWindowPanel$ConsolesPanel.create(LSPConsoleToolWindowPanel.java:115)
	at com.redhat.devtools.intellij.lsp4ij.console.LSPConsoleToolWindowPanel$ConsolesPanel.create(LSPConsoleToolWindowPanel.java:103)
	at com.intellij.ui.CardLayoutPanel.createValue(CardLayoutPanel.java:75)
	at com.intellij.ui.CardLayoutPanel.select(CardLayoutPanel.java:103)
	at com.intellij.ui.CardLayoutPanel.select(CardLayoutPanel.java:88)
	at com.redhat.devtools.intellij.lsp4ij.console.LSPConsoleToolWindowPanel.selectConsole(LSPConsoleToolWindowPanel.java:97)
	at com.redhat.devtools.intellij.lsp4ij.console.explorer.LanguageServerExplorer.onLanguageServerProcessSelected(LanguageServerExplorer.java:85)
	at com.redhat.devtools.intellij.lsp4ij.console.explorer.LanguageServerExplorer.lambda$new$0(LanguageServerExplorer.java:60)
	at java.desktop/javax.swing.JTree.fireValueChanged(JTree.java:2968)
	at java.desktop/javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3457)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:641)
	at com.intellij.ui.treeStructure.Tree$MySelectionModel.fireValueChanged(Tree.java:619)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1111)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:297)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:191)
	at java.desktop/javax.swing.JTree.setSelectionPath(JTree.java:1657)
	at com.redhat.devtools.intellij.lsp4ij.console.explorer.LanguageServerExplorer.selectAndExpand(LanguageServerExplorer.java:176)
	at com.redhat.devtools.intellij.lsp4ij.console.explorer.LanguageServerExplorerLifecycleListener.lambda$updateServerStatus$1(LanguageServerExplorerLifecycleListener.java:156)
	... 31 more
```
This seems related?

**Comment by angelozerr** [comment]
Fixed with https://github.com/redhat-developer/intellij-quarkus/pull/1013

Thanks so much @adietish !
