### ISSUE TITLE
"Read access is allowed from event dispatch thread or inside read-action only" when hovering in Qute templates

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/intellij-quarkus#882]
```
2023-05-24 09:11:53,884 [ 132367]  ERROR - plication.impl.ApplicationImpl - Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[JobScheduler FJ pool 5/11,4,Idea Thread Group] 1476663682
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 1026928875 
java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:177)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1033)
	at com.intellij.psi.impl.source.tree.TreeElement.assertReadAccessAllowed(TreeElement.java:411)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.findFileElement(SharedImplUtil.java:79)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getContainingFile(SharedImplUtil.java:54)
	at com.intellij.psi.impl.source.tree.LazyParseablePsiElement.getContainingFile(LazyParseablePsiElement.java:129)
	at com.intellij.psi.util.PsiUtil.getLanguageLevel(PsiUtil.java:1040)
	at com.intellij.psi.impl.source.JavaLightStubBuilder.isCodeBlockWithoutStubs(JavaLightStubBuilder.java:72)
	at com.intellij.psi.impl.source.JavaLightStubBuilder.skipChildProcessingWhenBuildingStubs(JavaLightStubBuilder.java:64)
	at com.intellij.psi.impl.source.tree.FileElement$1.visitComposite(FileElement.java:131)
	at com.intellij.psi.impl.source.tree.CompositeElement.acceptTree(CompositeElement.java:117)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor$1.visit(RecursiveTreeElementWalkingVisitor.java:67)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor$1.visit(RecursiveTreeElementWalkingVisitor.java:59)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:62)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:49)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitNode(RecursiveTreeElementWalkingVisitor.java:86)
	at com.intellij.psi.impl.source.tree.FileElement$1.visitComposite(FileElement.java:140)
	at com.intellij.psi.impl.source.tree.CompositeElement.acceptTree(CompositeElement.java:117)
	at com.intellij.psi.impl.source.tree.FileElement.calcStubbedDescendants(FileElement.java:127)
	at com.intellij.psi.impl.source.tree.FileElement.lambda$getStubbedSpine$0(FileElement.java:114)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.psi.impl.source.tree.FileElement.getStubbedSpine(FileElement.java:114)
	at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:176)
	at com.intellij.psi.impl.source.FileTrees.withAst(FileTrees.java:149)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:216)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:734)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:128)
	at com.intellij.psi.impl.source.PsiMethodImpl.getNode(PsiMethodImpl.java:245)
	at com.intellij.psi.impl.source.PsiMethodImpl.getDocComment(PsiMethodImpl.java:258)
	at com.redhat.devtools.intellij.quarkus.javadoc.JavadocContentAccess.getHTMLContentReader(JavadocContentAccess.java:26)
	at com.redhat.devtools.intellij.quarkus.javadoc.JavadocContentAccess.getPlainTextContentReader(JavadocContentAccess.java:67)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.internal.core.ls.PsiUtilsLSImpl.getJavadoc(PsiUtilsLSImpl.java:131)
	at com.redhat.devtools.intellij.qute.psi.QuteSupportForTemplate.getJavadoc(QuteSupportForTemplate.java:573)
	at com.redhat.devtools.intellij.qute.psi.QuteSupportForTemplate.getJavadoc(QuteSupportForTemplate.java:516)
	at com.redhat.devtools.intellij.qute.lsp.QuteLanguageClient.lambda$getJavadoc$18(QuteLanguageClient.java:185)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.IndexAwareLanguageClient.runTask(IndexAwareLanguageClient.java:97)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.IndexAwareLanguageClient$1.run(IndexAwareLanguageClient.java:76)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressInCurrentThread(CoreProgressManager.java:552)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:365)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.IndexAwareLanguageClient.lambda$runAsBackground$0(IndexAwareLanguageClient.java:73)
	at com.redhat.devtools.intellij.quarkus.lsp4ij.IndexAwareLanguageClient.lambda$runAsBackground$1(IndexAwareLanguageClient.java:87)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by fbricon** [comment]
Hover should be called within a `Application.runReadAction()` lambda

**Comment by fbricon** [comment]
this is just a very annoying error in the logs, but breaks nothing, so low severity

**Comment by fbricon** [comment]
closing as duplicate of #932
