### ISSUE TITLE
Cannot compute MicroProfile properties for the Java element `PsiClass:NativeConfig`.

### ISSUE THREAD

**Issue by gastaldi** [redhat-developer/intellij-quarkus#913]
To reproduce it, just browse a locally cloned version of https://github.com/quarkusio/registry.quarkus.io, the error should appear after the indexing finishes

```java
Cannot compute MicroProfile properties for the Java element 'PsiClass:NativeConfig'.

java.lang.IllegalArgumentException: Argument for @NotNull parameter 'qualifiedName' of com/intellij/psi/impl/JavaPsiFacadeImpl.findClass must not be null
	at com.intellij.psi.impl.JavaPsiFacadeImpl.$$$reportNull$$$0(JavaPsiFacadeImpl.java)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.utils.PsiTypeUtils.findType(PsiTypeUtils.java:147)
	at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:158)
	at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:216)
	at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.processConfigMapping(QuarkusConfigMappingProvider.java:120)
	at com.redhat.microprofile.psi.internal.quarkus.core.properties.QuarkusConfigMappingProvider.processAnnotation(QuarkusConfigMappingProvider.java:90)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.AbstractAnnotationTypeReferencePropertiesProvider.processAnnotation(AbstractAnnotationTypeReferencePropertiesProvider.java:58)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.AbstractAnnotationTypeReferencePropertiesProvider.collectProperties(AbstractAnnotationTypeReferencePropertiesProvider.java:48)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManager.collectProperties(PropertiesManager.java:126)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManager.lambda$getMicroProfileProjectInfo$1(PropertiesManager.java:103)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManager.lambda$getMicroProfileProjectInfo$2(PropertiesManager.java:103)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:143)
	at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:100)
	at com.redhat.devtools.intellij.quarkus.QuarkusProjectService.lambda$computeSchema$9(QuarkusProjectService.java:249)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:958)
	at com.redhat.devtools.intellij.quarkus.QuarkusProjectService.lambda$computeSchema$10(QuarkusProjectService.java:247)
	at com.intellij.openapi.project.SmartModeScheduler.doRun(SmartModeScheduler.kt:124)
	at com.intellij.openapi.project.SmartModeScheduler.runAllWhileSmart(SmartModeScheduler.kt:117)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:667)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:571)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:571)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by angelozerr** [comment]
@adietish if you see the stacktrace it is a diferent problem. It is a property compute problem but not the same usecase than #801

More #801 has been reeased

**Comment by adietish** [comment]
> It is a property compute problem but not the same usecase than #801

that's why it's related and not duplicate :)

**Comment by fbricon** [comment]
So [QuarkusConfigMappingProvider.populateConfigObject](https://github.com/redhat-developer/intellij-quarkus/blob/main/src/main/java/com/redhat/microprofile/psi/internal/quarkus/core/properties/QuarkusConfigMappingProvider.java#L146) fails while analyzing [NativeConfig.MonitoringOption](https://github.com/quarkusio/quarkus/blob/d87ef55647af0a8b6703e3ada5a6da130b139588/core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java#L485). It finds a method with no return type (i.e a constructor), which later on leads to the NPE. Turns out the .class file contains a private constructor, that doesn't exist in the source file.

**Comment by angelozerr** [comment]
> that's why it's related and not duplicate :)

OK I understand what you mean now :)

> Turns out the .class file contains a private constructor, that doesn't exist in the source file.

Thanks @fbricon for your detailled feedback.

We should see how quarkus ls JDT manages this usecase.

**Comment by angelozerr** [comment]
> We should see how quarkus ls JDT manages this usecase.

In Quarkus last version, the private enum `MonitoringOption`  in NativeConfig

```
package io.quarkus.deployment.pkg;

@ConfigMapping(prefix = "quarkus.native")
public interface NativeConfig {

  enum MonitoringOption {
        HEAPDUMP,
  }
}
```

In JDT MonitoringOption  is considred as IType, the following condidition is false https://github.com/redhat-developer/quarkus-ls/blob/8db8556d8fca360a9b898a91feb3cd76767ec550/quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/core/properties/QuarkusConfigMappingProvider.java#L139 and we don't try to compute properties for the enum

In IJ, enum MonitoringOption is considered as method (it is very strange), the folliwng condition is true https://github.com/redhat-developer/intellij-quarkus/blob/77c3ca4e8fe3ebb1df28667b73d4fb4aaf038cbb/src/main/java/com/redhat/microprofile/psi/internal/quarkus/core/properties/QuarkusConfigMappingProvider.java#L138

We need to check here https://github.com/redhat-developer/intellij-quarkus/blob/77c3ca4e8fe3ebb1df28667b73d4fb4aaf038cbb/src/main/java/com/redhat/microprofile/psi/internal/quarkus/core/properties/QuarkusConfigMappingProvider.java#L140 is the PsiMethod is an enum to ignore it.
