### ISSUE TITLE
Read access exception on completion on {@type } in qute template

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/intellij-quarkus#967]
in a qute template, try to complete on `{@String|`,  you'll get an exception:

```
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1048)
	at com.intellij.psi.impl.source.PsiFileImpl.assertReadAccessAllowed(PsiFileImpl.java:184)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:621)
	at com.intellij.psi.impl.source.PsiFileImpl.getGreenStubTree(PsiFileImpl.java:956)
	at com.intellij.psi.impl.source.SpineRef.getGreenStub(SpineRef.java:39)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getGreenStub(StubBasedPsiElementBase.java:352)
	at com.intellij.psi.impl.source.PsiClassImpl.getQualifiedName(PsiClassImpl.java:149)
	at com.redhat.devtools.intellij.qute.psi.internal.resolver.AbstractTypeResolver.resolveJavaTypeSignature(AbstractTypeResolver.java:54)
	at com.redhat.devtools.intellij.qute.psi.internal.template.JavaTypesSearch.lambda$collectClassesAndInterfaces$1(JavaTypesSearch.java:140)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.redhat.devtools.intellij.qute.psi.internal.template.JavaTypesSearch.collectClassesAndInterfaces(JavaTypesSearch.java:139)
	at com.redhat.devtools.intellij.qute.psi.internal.template.JavaTypesSearch.search(JavaTypesSearch.java:94)
	at com.redhat.devtools.intellij.qute.psi.QuteSupportForTemplate.getJavaTypes(QuteSupportForTemplate.java:161)
	at com.redhat.devtools.intellij.qute.lsp.QuteLanguageClient.lambda$getJavaTypes$5(QuteLanguageClient.java:133)
	at com.redhat.devtools.intellij.lsp4ij.IndexAwareLanguageClient.runTask(IndexAwareLanguageClient.java:60)
	at com.redhat.devtools.intellij.lsp4ij.IndexAwareLanguageClient$1.run(IndexAwareLanguageClient.java:39)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressInCurrentThread$10(CoreProgressManager.java:561)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressInCurrentThread(CoreProgressManager.java:561)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:381)
	at com.redhat.devtools.intellij.lsp4ij.IndexAwareLanguageClient.lambda$runAsBackground$0(IndexAwareLanguageClient.java:36)
	at com.redhat.devtools.intellij.lsp4ij.IndexAwareLanguageClient.lambda$runAsBackground$1(IndexAwareLanguageClient.java:50)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by angelozerr** [comment]
Once https://github.com/redhat-developer/intellij-quarkus/issues/955 will be done, I think it will fix this issue, no?
